package com.example.geminiv4.sqlite;
import java.util.ArrayList;
import java.util.LinkedHashMap;

public class NavicFishLandingCenters {




	public ArrayList<String> states = new ArrayList<String>();
	public ArrayList<LinkedHashMap<Integer, String>> landingcenters = new ArrayList<LinkedHashMap<Integer, String>>();
	public ArrayList<String> alllandingcenters = new ArrayList<String>();


	public static void main(String[] args) {

		System.out.println(new NavicFishLandingCenters().getFishLandingcenters("Gujarat"));
	}


	public LinkedHashMap<Integer, String> getFishLandingcenters(String state) {
		return landingcenters.get(states.indexOf(state));
	}




	public ArrayList<String> getFishLandingCenters(){
		ArrayList<String> landingcenter = new ArrayList<String>();
		landingcenter.add("Lakhapat");
		landingcenter.add("Kanoj");
		landingcenter.add("Narayan Sarovar (Koteshwar)");
		landingcenter.add("Guvar");
		landingcenter.add("Lakhi Bandar");
		landingcenter.add("Bhutau");
		landingcenter.add("Moti Akri");
		landingcenter.add("Mitha Port (Jakhau)");
		landingcenter.add("Jakhau");
		landingcenter.add("Kadoli");
		landingcenter.add("Khuada");
		landingcenter.add("Chhachhi");
		landingcenter.add("Bambhdai");
		landingcenter.add("Bhada");
		landingcenter.add("Nana Layja");
		landingcenter.add("Kanthada");
		landingcenter.add("Mandvi");
		landingcenter.add("Rawal Pir Dargah");
		landingcenter.add("Modhva");
		landingcenter.add("Tragdi");
		landingcenter.add("Tunda");
		landingcenter.add("Navinal");
		landingcenter.add("Zarpara");
		landingcenter.add("Mundra");
		landingcenter.add("Shekhadiya");
		landingcenter.add("Luni");
		landingcenter.add("Bhadreshwar");
		landingcenter.add("Kukadsar");
		landingcenter.add("Sanghad");
		landingcenter.add("Tuna Port");
		landingcenter.add("Tekra");
		landingcenter.add("Kandla");
		landingcenter.add("Navlakhi");
		landingcenter.add("Dabar Cr");
		landingcenter.add("Jodiya");
		landingcenter.add("Balachadi");
		landingcenter.add("Sachana");
		landingcenter.add("Kalyan Lt");
		landingcenter.add("Piroton Island");
		landingcenter.add("Sikka");
		landingcenter.add("Vadinar");
		landingcenter.add("Bharana");
		landingcenter.add("Nana Ambla");
		landingcenter.add("Salaya");
		landingcenter.add("Mota Asota");
		landingcenter.add("Poshitra");
		landingcenter.add("Okha");
		landingcenter.add("Mithapur");
		landingcenter.add("Kachchigadh");
		landingcenter.add("Rupen");
		landingcenter.add("Dwarka");
		landingcenter.add("Kuranga");
		landingcenter.add("Bhogat");
		landingcenter.add("Navadra");
		landingcenter.add("Harshad Miyani");
		landingcenter.add("Miyani");
		landingcenter.add("Tukda Miyani");
		landingcenter.add("Raatadi");
		landingcenter.add("Kuchhadi");
		landingcenter.add("Porbandar");
		landingcenter.add("odadar");
		landingcenter.add("Navibandar");
		landingcenter.add("Gorsar");
		landingcenter.add("Madhavpur");
		landingcenter.add("Shil");
		landingcenter.add("Mangrol");
		landingcenter.add("Mangrol Bara");
		landingcenter.add("Chorwad");
		landingcenter.add("Adri");
		landingcenter.add("Veraval");
		landingcenter.add("Hirakot");
		landingcenter.add("Kadwar");
		landingcenter.add("Sutrapada");
		landingcenter.add("Vadodra");
		landingcenter.add("Dhamlej");
		landingcenter.add("Mul Dwarka");
		landingcenter.add("Madhvad Lighthouse");
		landingcenter.add("Kotda");
		landingcenter.add("Diu Island");
		landingcenter.add("Nava Bandar");
		landingcenter.add("Simar");
		landingcenter.add("Saiyad Rajpara");
		landingcenter.add("Rohisha");
		landingcenter.add("Jafarabad");
		landingcenter.add("Shiyalbet");
		landingcenter.add("Pipavav");
		landingcenter.add("Patva");
		landingcenter.add("Gadhada");
		landingcenter.add("Mahuva (Bhavani Bandar)");
		landingcenter.add("Mahuva (Light House)");
		landingcenter.add("Nikol");
		landingcenter.add("Methla");
		landingcenter.add("Jhanjhmer");
		landingcenter.add("Gopnath");
		landingcenter.add("Sartanpar");
		landingcenter.add("Alang");
		landingcenter.add("Mithi Virdi");
		landingcenter.add("Haathab");
		landingcenter.add("Piram Bet");
		landingcenter.add("Badi");
		landingcenter.add("Ghogha");
		landingcenter.add("Bhavanagar New Port");
		landingcenter.add("Dungariya Bet");
		landingcenter.add("Kamatalav");
		landingcenter.add("Vadgam");
		landingcenter.add("Khambat");
		landingcenter.add("Surwada");
		landingcenter.add("Sarod");
		landingcenter.add("Kavi");
		landingcenter.add("Gangeshwar");
		landingcenter.add("Zamdi");
		landingcenter.add("Nadiyad");
		landingcenter.add("Tankari Pt");
		landingcenter.add("Asharsha");
		landingcenter.add("Denwa");
		landingcenter.add("Luvara");
		landingcenter.add("Mehgam");
		landingcenter.add("Dhanturia");
		landingcenter.add("Wansnoli");
		landingcenter.add("Bhadbhut");
		landingcenter.add("Oil Derrick");
		landingcenter.add("Kanthiajal");
		landingcenter.add("Kosamba (MangelVad)");
		landingcenter.add("Karanj");
		landingcenter.add("Mor");
		landingcenter.add("Marphalia");
		landingcenter.add("Gunav");
		landingcenter.add("Bhagal");
		landingcenter.add("Hazira");
		landingcenter.add("Dumas");
		landingcenter.add("Magadalla");
		landingcenter.add("Bhimpur");
		landingcenter.add("Dipla");
		landingcenter.add("Wasi Borsi");
		landingcenter.add("Dandi");
		landingcenter.add("Onjal Machhivad");
		landingcenter.add("Krishnapur");
		landingcenter.add("Bhat");
		landingcenter.add("Mendhar");
		landingcenter.add("Dholai");
		landingcenter.add("NaniDanti");
		landingcenter.add("Kakwadi");
		landingcenter.add("Bhadeli Jagalala");
		landingcenter.add("Valsad");
		landingcenter.add("Kosamba (Machhivad)");
		landingcenter.add("Magod Dungri");
		landingcenter.add("Umarsadi");
		landingcenter.add("Kolak");
		landingcenter.add("Bhimpor");
		landingcenter.add("Daman");
		landingcenter.add("Kalai");
		landingcenter.add("Fansa");
		landingcenter.add("Maroli");
		landingcenter.add("Tadgam");
		landingcenter.add("Kathalwada");
		landingcenter.add("Nargol");
		landingcenter.add("Umargam");
		landingcenter.add("Zai");
		landingcenter.add("Bordi");
		landingcenter.add("Gholvad");
		landingcenter.add("Narpad/DahanuAgar");
		landingcenter.add("Dahanu");
		landingcenter.add("Khondha Cr");
		landingcenter.add("DhaktiDahanu/Gungawada");
		landingcenter.add("Varor");
		landingcenter.add("Kambode");
		landingcenter.add("Ghivali");
		landingcenter.add("Tarapur Pt");
		landingcenter.add("PokharanDandi/Uchheli");
		landingcenter.add("Navapur (Ucheli Cr)");
		landingcenter.add("Murbe");
		landingcenter.add("Satpati(N)");
		landingcenter.add("Satpati(M/S)");
		landingcenter.add("Satpati");
		landingcenter.add("Shirgaon");
		landingcenter.add("Vadarai");
		landingcenter.add("Kelwane");
		landingcenter.add("Kelwa/KelwaDadar");
		landingcenter.add("Mahim Cr");
		landingcenter.add("Danda");
		landingcenter.add("Edavan/Kore");
		landingcenter.add("Datiware");
		landingcenter.add("Arnala");
		landingcenter.add("Tembhi");
		landingcenter.add("Arnalapada");
		landingcenter.add("Rangaon");
		landingcenter.add("MulgaonDanda");
		landingcenter.add("Vasai(Pachubandar)");
		landingcenter.add("Khochiwade");
		landingcenter.add("Vasai");
		landingcenter.add("Dongi Point");
		landingcenter.add("Dongri");
		landingcenter.add("Uttan");
		landingcenter.add("Uttan(Bhatye)");
		landingcenter.add("Gorai");
		landingcenter.add("Manori");
		landingcenter.add("Marve/Malvani");
		landingcenter.add("YerangalBhati");
		landingcenter.add("Madh");
		landingcenter.add("Patwadi");
		landingcenter.add("Vesava");
		landingcenter.add("Varsova");
		landingcenter.add("JuhumoraGaon");
		landingcenter.add("JuhuTara");
		landingcenter.add("KharDanda");
		landingcenter.add("Uarashi Rf");
		landingcenter.add("Chimbai");
		landingcenter.add("Mahim");
		landingcenter.add("Naigaon");
		landingcenter.add("Worli");
		landingcenter.add("Worli-Lotus");
		landingcenter.add("Malabar Port (Mumbai)");
		landingcenter.add("CuffPared");
		landingcenter.add("Colaba Pt.(Mumbai)");
		landingcenter.add("SasoonDock");
		landingcenter.add("Kalbadevi");
		landingcenter.add("Chinchbunder");
		landingcenter.add("NewFerryWharf");
		landingcenter.add("Trombay");
		landingcenter.add("Mahul");
		landingcenter.add("WashiBridge,PWDJetty");
		landingcenter.add("Vashi(Haveli)");
		landingcenter.add("Belapur");
		landingcenter.add("UlwaMoha");
		landingcenter.add("Morave-1");
		landingcenter.add("Nhawa");
		landingcenter.add("Dighode");
		landingcenter.add("Mora");
		landingcenter.add("HanumanKoliwada");
		landingcenter.add("Uran");
		landingcenter.add("Bhalpada");
		landingcenter.add("Waredi");
		landingcenter.add("Dharmtar Dhakka");
		landingcenter.add("Revas");
		landingcenter.add("Karanja Uran");
		landingcenter.add("Sasawane");
		landingcenter.add("Avas");
		landingcenter.add("Navgaon");
		landingcenter.add("Thal");
		landingcenter.add("VarsoliChalmala");
		landingcenter.add("Alibag");
		landingcenter.add("Nagaon");
		landingcenter.add("Theronda");
		landingcenter.add("Rewdanda");
		landingcenter.add("Boghar");
		landingcenter.add("Salav");
		landingcenter.add("Revadanda");
		landingcenter.add("Korlai");
		landingcenter.add("Borli-Mandla");
		landingcenter.add("Mazgaon");
		landingcenter.add("Ekdara");
		landingcenter.add("Murud");
		landingcenter.add("Rajpuri");
		landingcenter.add("Agardanda");
		landingcenter.add("Mandad");
		landingcenter.add("Pabhare");
		landingcenter.add("Kharsai");
		landingcenter.add("Kudgaon");
		landingcenter.add("Dighi(Savari)");
		landingcenter.add("Nanwell Pt");
		landingcenter.add("Bhardkhol-Diveagar");
		landingcenter.add("Diveagar");
		landingcenter.add("Shekhadi(Khalchi)");
		landingcenter.add("Srivardhan");
		landingcenter.add("Bagmandla");
		landingcenter.add("Veshawi-Bankot");
		landingcenter.add("Bankot");
		landingcenter.add("Velas");
		landingcenter.add("Kelshi");
		landingcenter.add("AadeUttambar");
		landingcenter.add("Anjarle");
		landingcenter.add("Paj");
		landingcenter.add("HarnePort");
		landingcenter.add("Harne");
		landingcenter.add("Murud");
		landingcenter.add("Burondi");
		landingcenter.add("Kolthare");
		landingcenter.add("Dabhol");
		landingcenter.add("Veldur/Navanagar/Dhopave");
		landingcenter.add("Tolkeshwar Pt");
		landingcenter.add("Anjanvel");
		landingcenter.add("Guhagar");
		landingcenter.add("Asgoli");
		landingcenter.add("Sakhar-Hedvi");
		landingcenter.add("Palshet");
		landingcenter.add("Budhal");
		landingcenter.add("Kondkarul");
		landingcenter.add("Welneshwar");
		landingcenter.add("Hedvi");
		landingcenter.add("Jaigad");
		landingcenter.add("SakharJaigad");
		landingcenter.add("Jaigarh Head");
		landingcenter.add("Varawade");
		landingcenter.add("Kharviwada");
		landingcenter.add("MTDC");
		landingcenter.add("Kalabadevi");
		landingcenter.add("SakhartarKasarveli");
		landingcenter.add("JakiMirya");
		landingcenter.add("Mirkarwada");
		landingcenter.add("Ratnagiri");
		landingcenter.add("Rajiwada");
		landingcenter.add("Rajiwada-Kerla");
		landingcenter.add("Someshvar");
		landingcenter.add("Phansop");
		landingcenter.add("Golap-Pawas");
		landingcenter.add("Purnagad");
		landingcenter.add("Purangad");
		landingcenter.add("Sakhri-Natye");
		landingcenter.add("Mavlanga");
		landingcenter.add("Ambere");
		landingcenter.add("Bokarwadi");
		landingcenter.add("Wada Vetye");
		landingcenter.add("Sakharinate");
		landingcenter.add("Ambolgad");
		landingcenter.add("PhansePadawane");
		landingcenter.add("Padve");
		landingcenter.add("Sakhar-Akshi");
		landingcenter.add("Wagapur Pt");
		landingcenter.add("Jambhari");
		landingcenter.add("Vijayadurg Hr");
		landingcenter.add("Vijaydurg");
		landingcenter.add("Kalamaiwadi");
		landingcenter.add("Wadatar/Malai");
		landingcenter.add("Anandwadi(Devgad)");
		landingcenter.add("Devgarh");
		landingcenter.add("Mithmumbri/Taramumbari");
		landingcenter.add("Kunkeshwar");
		landingcenter.add("Kunkeshwar/Katvan");
		landingcenter.add("Mithbao");
		landingcenter.add("Munge");
		landingcenter.add("Achra Pt");
		landingcenter.add("Achara");
		landingcenter.add("Tondavli");
		landingcenter.add("Hadi");
		landingcenter.add("Sarjekot-MiryaBandh");
		landingcenter.add("Talashil");
		landingcenter.add("Sarjekot");
		landingcenter.add("Dhurivada");
		landingcenter.add("Sindhudurg (Malvan)");
		landingcenter.add("Wayri");
		landingcenter.add("Tarkarli/Kalethar");
		landingcenter.add("Deobag");
		landingcenter.add("Kochara-Nivati");
		landingcenter.add("Khavana");
		landingcenter.add("Kelus");
		landingcenter.add("Mobar-Bhogave");
		landingcenter.add("Khanoli-Wayangani");
		landingcenter.add("Vengurla");
		landingcenter.add("Dabhoswada/Navabag");
		landingcenter.add("MuthUbhadanda");
		landingcenter.add("Mochemad");
		landingcenter.add("Shiroda");
		landingcenter.add("Redi");
		landingcenter.add("Terekhol");
		landingcenter.add("Chapora");
		landingcenter.add("Aguada");
		landingcenter.add("Panaji (Malim)");
		landingcenter.add("Santerem Pt (Vasco)");
		landingcenter.add("Majorde");
		landingcenter.add("Fatarde");
		landingcenter.add("Betul");
		landingcenter.add("Cutbona");
		landingcenter.add("Talpona");
		landingcenter.add("Kolamb");
		landingcenter.add("Majali");
		landingcenter.add("Sadasguvgarg");
		landingcenter.add("Karwar");
		landingcenter.add("Belekeri");
		landingcenter.add("Gangavali");
		landingcenter.add("Tadri");
		landingcenter.add("Kumta Pt");
		landingcenter.add("Dhareshvar");
		landingcenter.add("Karki");
		landingcenter.add("Honavar");
		landingcenter.add("Kasarkod");
		landingcenter.add("Navayatkere");
		landingcenter.add("Mavalli");
		landingcenter.add("Shirali");
		landingcenter.add("Bhatkal");
		landingcenter.add("Baindur");
		landingcenter.add("Navunda");
		landingcenter.add("Gangoli");
		landingcenter.add("Coondapoor (gangoli)");
		landingcenter.add("Kota");
		landingcenter.add("Hangarkatta");
		landingcenter.add("Malpe");
		landingcenter.add("Udiyavara");
		landingcenter.add("Kapu");
		landingcenter.add("Mulki");
		landingcenter.add("Hosabettu-Udaivar");
		landingcenter.add("Suratakal Pt");
		landingcenter.add("New Mangalore");
		landingcenter.add("Mangalore");
		landingcenter.add("Kunzhathur");
		landingcenter.add("Manjeshwara");
		landingcenter.add("Uppala");
		landingcenter.add("Arikkadi");
		landingcenter.add("Kumbla");
		landingcenter.add("Koipadi");
		landingcenter.add("Mogral");
		landingcenter.add("Adakathbail");
		landingcenter.add("Kasaragod");
		landingcenter.add("ThalangarJetty");
		landingcenter.add("Kotikulam");
		landingcenter.add("Bekal");
		landingcenter.add("Pallikere");
		landingcenter.add("Chittari");
		landingcenter.add("Ajanoor-N-Bella");
		landingcenter.add("Hosdrug");
		landingcenter.add("Nileswaram");
		landingcenter.add("Thaikadappuram");
		landingcenter.add("BadagaraAzhithala");
		landingcenter.add("CheruvathurFH");
		landingcenter.add("Maniyat");
		landingcenter.add("Kavvayi");
		landingcenter.add("Kunnariyam");
		landingcenter.add("Ettikulam");
		landingcenter.add("Kotte Kunnu");
		landingcenter.add("Koloth");
		landingcenter.add("Azhikal");
		landingcenter.add("Valapattanam");
		landingcenter.add("Azheecode");
		landingcenter.add("AzheecodeSouth");
		landingcenter.add("Kannur");
		landingcenter.add("AyikkaraFH");
		landingcenter.add("Edakkad");
		landingcenter.add("Muzhuppilangad");
		landingcenter.add("Tellicherry");
		landingcenter.add("NewMahe");
		landingcenter.add("ChombalaFH");
		landingcenter.add("Uralungal");
		landingcenter.add("Nalliyankara");
		landingcenter.add("Badagara");
		landingcenter.add("Puduppanam");
		landingcenter.add("Kottakkal");
		landingcenter.add("Kizhur");
		landingcenter.add("Tikkoti");
		landingcenter.add("Moodady");
		landingcenter.add("Thikkodi(Kodikkal)");
		landingcenter.add("Kadalur Pt");
		landingcenter.add("Quilandy/Koloth(Defunct)");
		landingcenter.add("Kollam");
		landingcenter.add("Poilkavu");
		landingcenter.add("Chemancheri");
		landingcenter.add("Kappad");
		landingcenter.add("Elathur");
		landingcenter.add("PuthiyappaFH");
		landingcenter.add("Puthengadi/Paravanna");
		landingcenter.add("Kunduparabu");
		landingcenter.add("Nadakkavu");
		landingcenter.add("Vellayil");
		landingcenter.add("Calicut");
		landingcenter.add("VadakkeKadappuram");
		landingcenter.add("BeyporeFH");
		landingcenter.add("Ramanattukara");
		landingcenter.add("Chaliyam");
		landingcenter.add("Beypore");
		landingcenter.add("Kadalundinagaram");
		landingcenter.add("Parapanangadi");
		landingcenter.add("Thanur");
		landingcenter.add("Paravannangadi");
		landingcenter.add("Vakkad");
		landingcenter.add("Koottayi");
		landingcenter.add("Purattur");
		landingcenter.add("Ponnani");
		landingcenter.add("Veliyangod");
		landingcenter.add("Palappetty");
		landingcenter.add("Attupuram");
		landingcenter.add("Mannalamkunnu");
		landingcenter.add("Vayilattur");
		landingcenter.add("Panchavadi");
		landingcenter.add("Edakazhiyur");
		landingcenter.add("Blangad");
		landingcenter.add("Chavakkad");
		landingcenter.add("Mullassheri");
		landingcenter.add("Vadanappally");
		landingcenter.add("Thalikulam");
		landingcenter.add("Nattika");
		landingcenter.add("Kazhimbram");
		landingcenter.add("Edamuttam");
		landingcenter.add("Palapetty");
		landingcenter.add("KaipamangalamVanchipura");
		landingcenter.add("PerinjanamAraattukadavu");
		landingcenter.add("Kulimuttam");
		landingcenter.add("Kara");
		landingcenter.add("Pullut");
		landingcenter.add("Eriyad(Chelarappa)");
		landingcenter.add("Kodungallur");
		landingcenter.add("MunambamFH");
		landingcenter.add("Manakodam");
		landingcenter.add("Kuzhuppilly");
		landingcenter.add("Cherai");
		landingcenter.add("Edavanakad");
		landingcenter.add("Vadakkal");
		landingcenter.add("Puthenkadappuram");
		landingcenter.add("Narakkal");
		landingcenter.add("Nayarambalam");
		landingcenter.add("Malipuram");
		landingcenter.add("Ernakulam");
		landingcenter.add("Murikumpadam");
		landingcenter.add("Kalamukku");
		landingcenter.add("Vypeen");
		landingcenter.add("Valarpadam");
		landingcenter.add("FortKochi");
		landingcenter.add("Kochi");
		landingcenter.add("Chillickal");
		landingcenter.add("Puthenthodu(Kannamali)");
		landingcenter.add("Maruvakad");
		landingcenter.add("Chellanum");
		landingcenter.add("Pallithodu");
		landingcenter.add("Manakkodam");
		landingcenter.add("Thykal");
		landingcenter.add("Arthunkal/Chennavely");
		landingcenter.add("Aratungal");
		landingcenter.add("Chethy");
		landingcenter.add("Kottamkulangara");
		landingcenter.add("Pollethai");
		landingcenter.add("Thumpolly");
		landingcenter.add("Thazhampally");
		landingcenter.add("AlleppeyBeach");
		landingcenter.add("Kalarkod");
		landingcenter.add("Punnappra");
		landingcenter.add("Valanjavazhy");
		landingcenter.add("Ambalapuzha");
		landingcenter.add("Purakkad");
		landingcenter.add("Thottappally");
		landingcenter.add("Thrikunnapuzha");
		landingcenter.add("Padiyamkara Tekku");
		landingcenter.add("Ramancheri Tura");
		landingcenter.add("AzheekalJetty");
		landingcenter.add("Alappattu");
		landingcenter.add("Cheriazheekal");
		landingcenter.add("Kovilthottam");
		landingcenter.add("Chavara");
		landingcenter.add("Puthenthura");
		landingcenter.add("Vettuthura");
		landingcenter.add("Neendakara");
		landingcenter.add("Sakthikulangara");
		landingcenter.add("Thankassery F.H.");
		landingcenter.add("QuilonPort");
		landingcenter.add("Quilon");
		landingcenter.add("Wadi");
		landingcenter.add("Moothakara");
		landingcenter.add("Pallithottam");
		landingcenter.add("Eravipuram");
		landingcenter.add("Tanni");
		landingcenter.add("Pozhikkara");
		landingcenter.add("Paravoor");
		landingcenter.add("Edava");
		landingcenter.add("Kappil");
		landingcenter.add("Edaval");
		landingcenter.add("Vettoor");
		landingcenter.add("Chilakkoor");
		landingcenter.add("Arivalam&Rathikkal");
		landingcenter.add("Mampally");
		landingcenter.add("AnjengoNorth");
		landingcenter.add("AnjengoSouth");
		landingcenter.add("Poothura");
		landingcenter.add("Perumathura");
		landingcenter.add("Puthukurichi");
		landingcenter.add("Puthenthoppu");
		landingcenter.add("St.Andrews");
		landingcenter.add("Pallithura");
		landingcenter.add("Thumba");
		landingcenter.add("Valiaveli");
		landingcenter.add("Kochuveli");
		landingcenter.add("Vell");
		landingcenter.add("Vettucaud");
		landingcenter.add("Kannanthura");
		landingcenter.add("Kochuthoppu");
		landingcenter.add("Trivandrum");
		landingcenter.add("Valiathura/ValiathuraPier");
		landingcenter.add("Cheriathura");
		landingcenter.add("Bheemapally");
		landingcenter.add("Poonthura");
		landingcenter.add("Tiruvallam");
		landingcenter.add("PanathuraSouth");
		landingcenter.add("Kovalad");
		landingcenter.add("Vizhinjam&Kottapuram");
		landingcenter.add("Vizhinjam");
		landingcenter.add("VizhinjamNorth");
		landingcenter.add("Mariyanadu");
		landingcenter.add("Adimalathura");
		landingcenter.add("Puthiathura(Kochupally)");
		landingcenter.add("Karichal");
		landingcenter.add("Puthiathura(Chinnamarthandanthura)");
		landingcenter.add("Kochuthura");
		landingcenter.add("Poovar");
		landingcenter.add("Neerodi");
		landingcenter.add("Marthandamthurai");
		landingcenter.add("Vallavilai");
		landingcenter.add("Eraviputhenthurai");
		landingcenter.add("Ezhudesam Chinnathurai");
		landingcenter.add("Thoothur");
		landingcenter.add("Poothurai");
		landingcenter.add("Erayammanthura");
		landingcenter.add("Erayumanthurai");
		landingcenter.add("Thengapattanam");
		landingcenter.add("Mulloorthurai");
		landingcenter.add("Ramanthurai");
		landingcenter.add("Enayam puthenthurai");
		landingcenter.add("Enayam Chinnathurai");
		landingcenter.add("Enayam");
		landingcenter.add("Midaalam");
		landingcenter.add("Midalam (Naduthurai");
		landingcenter.add("Kurumbanai");
		landingcenter.add("Vaniyakudi");
		landingcenter.add("Kodimunai");
		landingcenter.add("Simon colony");
		landingcenter.add("Colachel");
		landingcenter.add("Kottilpadu");
		landingcenter.add("Mandaikadu puthoor");
		landingcenter.add("Periavilai");
		landingcenter.add("Chinnavilai");
		landingcenter.add("Melakadiapattinam");
		landingcenter.add("Kovalam");
		landingcenter.add("Keezhakadiapattinam");
		landingcenter.add("Melamuttom");
		landingcenter.add("Muttom");
		landingcenter.add("Azhikkal");
		landingcenter.add("Rajakkamanglam");
		landingcenter.add("Rajakamangalam Thurai");
		landingcenter.add("Periyakadu");
		landingcenter.add("Pozhikkarai");
		landingcenter.add("Kesavanputhenthurai");
		landingcenter.add("Puthenthurai");
		landingcenter.add("Pallam");
		landingcenter.add("Keezhamanakudi");
		landingcenter.add("Mela Manakudi");
		landingcenter.add("Kovalam Kanniyakumarai");
		landingcenter.add("Puthur");
		landingcenter.add("Puthugramam (Vavuthurai");
		landingcenter.add("Kanniyakumari");
		landingcenter.add("Chinnamuttom");
		landingcenter.add("Lipuram");
		landingcenter.add("Arockiyapuram");
		landingcenter.add("Kuttapuli");
		landingcenter.add("Chettikulam");
		landingcenter.add("Perumanal");
		landingcenter.add("Kudangulam");
		landingcenter.add("Idinthakarai");
		landingcenter.add("Perumanal");
		landingcenter.add("Thommayarpuram(Muddukuli");
		landingcenter.add("Koothanguzhi");
		landingcenter.add("Kundal");
		landingcenter.add("Uvari");
		landingcenter.add("Koottappanai");
		landingcenter.add("Kooduthalai");
		landingcenter.add("Periyathalai");
		landingcenter.add("Manappad Pt");
		landingcenter.add("Kulasekharapattinam");
		landingcenter.add("Kallamozhi");
		landingcenter.add("Alanthalai");
		landingcenter.add("Amalinagar");
		landingcenter.add("Jeevanagar");
		landingcenter.add("Veerapandiyapattinam");
		landingcenter.add("Singhithurai");
		landingcenter.add("Kombuthurai Madhakoil");
		landingcenter.add("Punnakkayal");
		landingcenter.add("Ratchanyapuram");
		landingcenter.add("Tuticorin");
		landingcenter.add("Pandyan");
		landingcenter.add("Inico nagar");
		landingcenter.add("Thoothukudi");
		landingcenter.add("Therespuram");
		landingcenter.add("Thalamuthunagar");
		landingcenter.add("Vellapatti");
		landingcenter.add("Tharuvaikulam");
		landingcenter.add("Pattanamarudur");
		landingcenter.add("Veppalodai");
		landingcenter.add("Sippikulam");
		landingcenter.add("Keezhavaippar");
		landingcenter.add("Periasamypuram");
		landingcenter.add("Vembar");
		landingcenter.add("Rojma Nagar");
		landingcenter.add("Terku Mookkaiyur");
		landingcenter.add("Valinokkam");
		landingcenter.add("Chinna Ervadi");
		landingcenter.add("Kilakarai");
		landingcenter.add("Kalimankundu");
		landingcenter.add("Muttupettai");
		landingcenter.add("Inthira Nagar");
		landingcenter.add("Valangapuri");
		landingcenter.add("Seeniyappa Dharga");
		landingcenter.add("Vedhalai");
		landingcenter.add("Mandapam (South)");
		landingcenter.add("Chinnapalam");
		landingcenter.add("Pamban Kunthukal");
		landingcenter.add("Mukuntharayarchatram");
		landingcenter.add("Dhanushkodi");
		landingcenter.add("Verkode");
		landingcenter.add("Rameshwaram Harbour");
		landingcenter.add("Olaikuda");
		landingcenter.add("Villundi");
		landingcenter.add("Thangachimadam");
		landingcenter.add("Pamban Light House");
		landingcenter.add("Mandpam (North)");
		landingcenter.add("Munaikadu");
		landingcenter.add("Atrangarai");
		landingcenter.add("Alagankulam");
		landingcenter.add("Pudukkudi");
		landingcenter.add("Panaikulam");
		landingcenter.add("Pudhuvalasaichathiram");
		landingcenter.add("Palanivalasai");
		landingcenter.add("Mudiveeranpattinam");
		landingcenter.add("Devipattinam South");
		landingcenter.add("Devipattinam");
		landingcenter.add("Pathanendal");
		landingcenter.add("Thirupalaikudi North");
		landingcenter.add("Moreppanai");
		landingcenter.add("Karankadu");
		landingcenter.add("Mullimanai");
		landingcenter.add("Pudhupattinam");
		landingcenter.add("Tiruvettriyur");
		landingcenter.add("Soliyakudi Harbour");
		landingcenter.add("Nambuthalai");
		landingcenter.add("Tondi");
		landingcenter.add("M.R.Pattinam");
		landingcenter.add("Valasapatinam(P.V.Pattinam");
		landingcenter.add("Narendhal");
		landingcenter.add("Dhamotharanpattinam");
		landingcenter.add("Pasipattinam");
		landingcenter.add("Theerthaandathanam");
		landingcenter.add("Sundarapandiyanpatta");
		landingcenter.add("Muthukuda");
		landingcenter.add("R.Pudhupattinam");
		landingcenter.add("Gopalapattinam");
		landingcenter.add("Muthanenthal");
		landingcenter.add("Ayyampattinam");
		landingcenter.add("Kottaippattanam");
		landingcenter.add("Pudhukkudi South");
		landingcenter.add("Pudhukkudi North");
		landingcenter.add("Anthoniyarpuram");
		landingcenter.add("Ponagaram");
		landingcenter.add("Manamelkudi");
		landingcenter.add("Keelakudiyiruppu");
		landingcenter.add("Vadakku Amapattinam");
		landingcenter.add("Seetharampattinam");
		landingcenter.add("Krishnajipattinam");
		landingcenter.add("Prathaparamanpattinam");
		landingcenter.add("Kattumavadi");
		landingcenter.add("Sembiyanmadevipattinam");
		landingcenter.add("Ganesapuram");
		landingcenter.add("Vallavanpattinam");
		landingcenter.add("Subbamachatram");
		landingcenter.add("Somanathanpattinam");
		landingcenter.add("Annanagar Pudhutheru");
		landingcenter.add("Mandhiripattinam");
		landingcenter.add("Senthalaivayal");
		landingcenter.add("Adaikkadevan");
		landingcenter.add("Sambaipattinam");
		landingcenter.add("Karanguda");
		landingcenter.add("Kazhumanguda");
		landingcenter.add("Sethubavachattram");
		landingcenter.add("Pillayarthidal");
		landingcenter.add("Chinnamanai");
		landingcenter.add("Mallipattinam");
		landingcenter.add("Puthupattinam");
		landingcenter.add("Velivayal");
		landingcenter.add("Kollukadu");
		landingcenter.add("Keelathottam");
		landingcenter.add("Eripurakkarai");
		landingcenter.add("Gandhinagar");
		landingcenter.add("Karaiyurtheru");
		landingcenter.add("Maravakadu");
		landingcenter.add("Thambikottai");
		landingcenter.add("Muthupet");
		landingcenter.add("Point Calimer");
		landingcenter.add("Kodiyakarai");
		landingcenter.add("Vedaranniyam");
		landingcenter.add("Arkkattuthurai");
		landingcenter.add("Topputturai");
		landingcenter.add("Pushpavanam");
		landingcenter.add("Kallinodu");
		landingcenter.add("Vellapallam");
		landingcenter.add("Vanavanmadevi");
		landingcenter.add("Vettaikaranrippu");
		landingcenter.add("Vilunthamavadi");
		landingcenter.add("Kameshwaram");
		landingcenter.add("Seruthur");
		landingcenter.add("Velanganni");
		landingcenter.add("Akkaraipettai");
		landingcenter.add("Nagapattinam Harbour");
		landingcenter.add("Nambiyar Nagar");
		landingcenter.add("Samanthanpettai");
		landingcenter.add("Nagore");
		landingcenter.add("Karikal");
		landingcenter.add("Pattinacherry");
		landingcenter.add("Chinnorpettai");
		landingcenter.add("Chandrappadi");
		landingcenter.add("Tharangampadi");
		landingcenter.add("Kuttiyandiyur");
		landingcenter.add("Bommayanpettai (Vellakoil");
		landingcenter.add("Perumalpettai");
		landingcenter.add("Tranquebar");
		landingcenter.add("Pudhupettai");
		landingcenter.add("Thalampettai");
		landingcenter.add("Chinnangudi");
		landingcenter.add("Kaverippattinam");
		landingcenter.add("Vanagiri");
		landingcenter.add("Poombuhar");
		landingcenter.add("Pudukuppam");
		landingcenter.add("Madathukuppam");
		landingcenter.add("Naickerkuppam");
		landingcenter.add("Chavadikuppam");
		landingcenter.add("Keezhamoovarkarai");
		landingcenter.add("Tirumullaivasal");
		landingcenter.add("Thoduvai");
		landingcenter.add("Mudasalodai Village");
		landingcenter.add("Koozhayar");
		landingcenter.add("Kottaimedu");
		landingcenter.add("Madavamedu");
		landingcenter.add("Pazhayar");
		landingcenter.add("Killai");
		landingcenter.add("M.G.R. Thittu");
		landingcenter.add("Mudasalodai");
		landingcenter.add("Parangipettai");
		landingcenter.add("Portonovo");
		landingcenter.add("C Pudupettai");
		landingcenter.add("Pudukuppam");
		landingcenter.add("Veerampatinam");
		landingcenter.add("Samanthapettai");
		landingcenter.add("Samiyarpettai");
		landingcenter.add("Kumarapettai");
		landingcenter.add("Periyakuppam");
		landingcenter.add("Chithiraipettai");
		landingcenter.add("Rajappettai");
		landingcenter.add("Sothikuppam");
		landingcenter.add("Cuddalore Harbour");
		landingcenter.add("Sonaankuppam");
		landingcenter.add("Devanampattinam");
		landingcenter.add("Thazhanguda");
		landingcenter.add("Moorthipudukuppam");
		landingcenter.add("Panithittu");
		landingcenter.add("Narambai");
		landingcenter.add("Nallavadu");
		landingcenter.add("P. Pudukuppam");
		landingcenter.add("Chinna Veerampattinam");
		landingcenter.add("Veerampattinam");
		landingcenter.add("Thengaithittu");
		landingcenter.add("Pondicherry");
		landingcenter.add("Vaithikuppam");
		landingcenter.add("Solainagar North");
		landingcenter.add("Sodhanaikuppam");
		landingcenter.add("Nadukuppam");
		landingcenter.add("Thandhirayankuppam");
		landingcenter.add("Chinna mudaliarchavadi");
		landingcenter.add("Bommaiyarpalyam");
		landingcenter.add("Pillaichavadi");
		landingcenter.add("Periya Kalapet");
		landingcenter.add("Ganapathichettikulam");
		landingcenter.add("Pudhukuppam");
		landingcenter.add("Anichankuppam");
		landingcenter.add("Mudaliarkuppam");
		landingcenter.add("Nochikuppam");
		landingcenter.add("Koonimedu Kuppam");
		landingcenter.add("Chettinagar");
		landingcenter.add("Anumandhaikuppam");
		landingcenter.add("Komuttichavadikuppam");
		landingcenter.add("Mandavai Pudukuppam");
		landingcenter.add("Ekkiyarkuppam");
		landingcenter.add("Marakkanam");
		landingcenter.add("Kaippanikuppam");
		landingcenter.add("Vasavankuppam");
		landingcenter.add("Muttukaduazhagankuppam");
		landingcenter.add("Alambaraikuppam");
		landingcenter.add("Kadappakam");
		landingcenter.add("Panaiyur Periya Kuppam");
		landingcenter.add("Panaiyur Chinnakuppam");
		landingcenter.add("Mudaliyar Kuppam");
		landingcenter.add("Cheyyur");
		landingcenter.add("Paramankeni");
		landingcenter.add("Perun Thuravu Kuppam");
		landingcenter.add("Pudhunadukuppam");
		landingcenter.add("Pazhayanadukuppam");
		landingcenter.add("Angalamman Kuppam");
		landingcenter.add("Kadalore Ali Kuppam");
		landingcenter.add("Padalore Periya Kuppam");
		landingcenter.add("Kadalore Chinna Kuppam");
		landingcenter.add("Uyyalikuppam");
		landingcenter.add("Sadras");
		landingcenter.add("Pudupattinam");
		landingcenter.add("Sathurangapattinam");
		landingcenter.add("Umarikuppam");
		landingcenter.add("Meyyurkuppam");
		landingcenter.add("Kokilamedu");
		landingcenter.add("Venpursham");
		landingcenter.add("Mamallapuram");
		landingcenter.add("Mahabalipuram");
		landingcenter.add("Devaneri");
		landingcenter.add("Salavankuppam");
		landingcenter.add("Pudu Nemeli Kuppam");
		landingcenter.add("Pattipulam");
		landingcenter.add("Soolerikattukuppam");
		landingcenter.add("Nemmelikuppam");
		landingcenter.add("Pudhukalpakkam");
		landingcenter.add("Chemacherry");
		landingcenter.add("Covelong (Kovalam)");
		landingcenter.add("Egattur Karikattukuppam");
		landingcenter.add("Kanathur Reddy Kuppam");
		landingcenter.add("Kanathur");
		landingcenter.add("Nainarkuppam");
		landingcenter.add("Panaiyurkuppam");
		landingcenter.add("Injampakkam");
		landingcenter.add("Chinnandikuppam");
		landingcenter.add("Periya Neelankarai");
		landingcenter.add("Chinna Neelankarai");
		landingcenter.add("Palavakkam");
		landingcenter.add("Kottivakkam");
		landingcenter.add("Thiruvanmiyur");
		landingcenter.add("Odaikuppam");
		landingcenter.add("Orurkuppam");
		landingcenter.add("Srinivasapuram");
		landingcenter.add("Mullimanagar");
		landingcenter.add("Pattinampakkam");
		landingcenter.add("Nochikuppam");
		landingcenter.add("Cathedral (Chennai)");
		landingcenter.add("Nadukuppam");
		landingcenter.add("Ayothikuppam");
		landingcenter.add("Mattankuppam");
		landingcenter.add("Chennai");
		landingcenter.add("Lakshmipuram Odaikuppam");
		landingcenter.add("Royapuram");
		landingcenter.add("Ondikuppam");
		landingcenter.add("Nallathanneer Odaikuppam");
		landingcenter.add("Thiruchinnankuppam");
		landingcenter.add("Kasiviswanathar koil Kuppam");
		landingcenter.add("Palagaithottikuppam");
		landingcenter.add("Kasikoilkuppam");
		landingcenter.add("Ernavoorkuppam");
		landingcenter.add("Kathivakkam Chinnakuppam");
		landingcenter.add("Kathivakkam Periakuppam");
		landingcenter.add("Thazankuppam");
		landingcenter.add("Ennore Mugathuvarakuppan");
		landingcenter.add("Ennorekuppam");
		landingcenter.add("Pulicat");
		landingcenter.add("Coromandel");
		landingcenter.add("Annamalaichery");
		landingcenter.add("Periyamangodu");
		landingcenter.add("Arambakkam");
		landingcenter.add("Pulinjerikuppam");
		landingcenter.add("Durgarajupatnam");
		landingcenter.add("Kondur");
		landingcenter.add("Arkatapalem");
		landingcenter.add("Kottapatnam");
		landingcenter.add("Tammenapatnam");
		landingcenter.add("Krishnapatnam(Upputeru)");
		landingcenter.add("Krishnapatnam");
		landingcenter.add("Pathapalem");
		landingcenter.add("Maipadu");
		landingcenter.add("Pattapupalem");
		landingcenter.add("Utukuru");
		landingcenter.add("Isakapalle");
		landingcenter.add("Zuvvaladinne");
		landingcenter.add("Vatturupallepalem");
		landingcenter.add("Ramayapatnam");
		landingcenter.add("Chakicherla");
		landingcenter.add("Itamukkala");
		landingcenter.add("Allurukottapatnam");
		landingcenter.add("Adavipallipalem");
		landingcenter.add("Vetapalem");
		landingcenter.add("Vadarevu");
		landingcenter.add("Bestapalam Bapatla");
		landingcenter.add("Suryalanka");
		landingcenter.add("Nizampatnam");
		landingcenter.add("Nachugunta");
		landingcenter.add("Etimoga");
		landingcenter.add("Sorlagondi");
		landingcenter.add("Palakayatippa");
		landingcenter.add("Machilipatnam");
		landingcenter.add("Giripuram");
		landingcenter.add("Pedda Gollapalem");
		landingcenter.add("Antarvedi");
		landingcenter.add("Narasapur Pt");
		landingcenter.add("Bandamurlanka");
		landingcenter.add("Odalarevu");
		landingcenter.add("Kothapalem LH");
		landingcenter.add("Bhairavapalem");
		landingcenter.add("Kakinada");
		landingcenter.add("Vakalapudi");
		landingcenter.add("Uppada");
		landingcenter.add("Konapapeta");
		landingcenter.add("Perumallapuram");
		landingcenter.add("Palmanpeta");
		landingcenter.add("Danavaipeta");
		landingcenter.add("Pentakota");
		landingcenter.add("Revu Polavaram");
		landingcenter.add("Rambilli");
		landingcenter.add("Pudimadaka");
		landingcenter.add("Visakhapatnam");
		landingcenter.add("Bhimunipatnam");
		landingcenter.add("Mukkam");
		landingcenter.add("Konada");
		landingcenter.add("Chintapalli");
		landingcenter.add("Ramachandrapuram");
		landingcenter.add("Allivalasa");
		landingcenter.add("Kuppili");
		landingcenter.add("Srikurmam");
		landingcenter.add("Bandaruvanipeta");
		landingcenter.add("Kalingapatnam");
		landingcenter.add("Guppidipeta");
		landingcenter.add("Jagannadhapuram");
		landingcenter.add("Maruvada");
		landingcenter.add("Kotta Naupada");
		landingcenter.add("Bavanapadu");
		landingcenter.add("Nuvvalarevu");
		landingcenter.add("Metturu");
		landingcenter.add("Ganguvada");
		landingcenter.add("Baruva");
		landingcenter.add("Iduvanipalem");
		landingcenter.add("Kaviti");
		landingcenter.add("Anantaraipur");
		landingcenter.add("KeutaSonapur");
		landingcenter.add("PatiSonapur");
		landingcenter.add("Sonnapurampeta");
		landingcenter.add("Rameyapatna");
		landingcenter.add("Ekasingi");
		landingcenter.add("Markondi");
		landingcenter.add("New Golabandha");
		landingcenter.add("Gopalpur-IFH");
		landingcenter.add("Golabandha");
		landingcenter.add("Old Buxipetta");
		landingcenter.add("NewBaxipalli");
		landingcenter.add("Gopalpur");
		landingcenter.add("Garyampetta");
		landingcenter.add("Sana Aryapalli");
		landingcenter.add("BadaNuagaon");
		landingcenter.add("SanaNuagaon");
		landingcenter.add("Ganjam");
		landingcenter.add("Kantiagada(Podampeta)");
		landingcenter.add("Prayagi");
		landingcenter.add("Ramalanka");
		landingcenter.add("Bajarkot");
		landingcenter.add("Khirisahi");
		landingcenter.add("Satpara");
		landingcenter.add("Siandi");
		landingcenter.add("Arakhakud");
		landingcenter.add("PuriNorth");
		landingcenter.add("PuriSouth");
		landingcenter.add("Puri");
		landingcenter.add("Penthakata");
		landingcenter.add("Bangor");
		landingcenter.add("Chandrabhaga");
		landingcenter.add("Kajalpatia(Khandiapatna)");
		landingcenter.add("Tondahar");
		landingcenter.add("Anakona&Dalukani");
		landingcenter.add("Astaranga");
		landingcenter.add("Balipantala");
		landingcenter.add("Sudhikeswar(Talia)");
		landingcenter.add("NuagarhFH(Astaranga)");
		landingcenter.add("Nuagar");
		landingcenter.add("Bandar");
		landingcenter.add("Magarkhia");
		landingcenter.add("Saharabedi");
		landingcenter.add("Kaliakana");
		landingcenter.add("Noliasahi");
		landingcenter.add("Nuagan");
		landingcenter.add("Jamuka");
		landingcenter.add("ParadeepFH");
		landingcenter.add("Paradip");
		landingcenter.add("Atharabanki");
		landingcenter.add("Chumuhani");
		landingcenter.add("Kharnasi");
		landingcenter.add("False Point");
		landingcenter.add("Kharinasi");
		landingcenter.add("Jambu");
		landingcenter.add("Jmboo");
		landingcenter.add("Barunie");
		landingcenter.add("Sasanpeta(Tantiapal)");
		landingcenter.add("Gajarajpur");
		landingcenter.add("Hariharpur");
		landingcenter.add("Satbhaya");
		landingcenter.add("Ahirajpur");
		landingcenter.add("Talchua");
		landingcenter.add("Dhamra");
		landingcenter.add("Chandinipal");
		landingcenter.add("DhamaraFH");
		landingcenter.add("Kaithakhola");
		landingcenter.add("Karanjamal");
		landingcenter.add("Baincha");
		landingcenter.add("Karanpalli");
		landingcenter.add("Kasianala");
		landingcenter.add("ChudamaniBoatJetty");
		landingcenter.add("Chudamani");
		landingcenter.add("Panchubisa");
		landingcenter.add("Godaisagar");
		landingcenter.add("Janipur");
		landingcenter.add("Mahisali");
		landingcenter.add("Chandipur");
		landingcenter.add("Balaramgadi(ChandipurFLC)");
		landingcenter.add("Balaramgadi");
		landingcenter.add("Bahabalapur(KasafalSouth)");
		landingcenter.add("Bahabalpur");
		landingcenter.add("Bindha");
		landingcenter.add("Hansakura");
		landingcenter.add("Kasafala");
		landingcenter.add("Choumukh");
		landingcenter.add("Dagara");
		landingcenter.add("Kirtania");
		landingcenter.add("Chandeneswar");
		landingcenter.add("Talasari");
		landingcenter.add("DighaMohanaF.F.T.A.(Digha)");
		landingcenter.add("Shankarpur");
		landingcenter.add("SankarpurF.F.T.A.(Sankarpur)");
		landingcenter.add("TajpurJaldha");
		landingcenter.add("Digha");
		landingcenter.add("Junput");
		landingcenter.add("Petuaghat (Dariapur)");
		landingcenter.add("LightHouse,GangasagarGP");
		landingcenter.add("DiamondHarbour Jetty Ghat");
		landingcenter.add("Diamond Harbour");
		landingcenter.add("Kakdwip");
		landingcenter.add("Namkhana");
		landingcenter.add("Sagar");
		landingcenter.add("Frasergunje");
		landingcenter.add("FrezerganjFH");
		landingcenter.add("Lothian Island");
		landingcenter.add("Landfall");
		landingcenter.add("Narcondam");
		landingcenter.add("Diglipur");
		landingcenter.add("Laxmipur,Diglipur");
		landingcenter.add("ArealBay,Diglipur");
		landingcenter.add("Durgapur");
		landingcenter.add("Kalipur,Diglipur");
		landingcenter.add("Kalighat,Diglipur");
		landingcenter.add("Pokadera");
		landingcenter.add("Mayabunderproper");
		landingcenter.add("Webi,Mayabunder");
		landingcenter.add("Tugapur,Mayabunder");
		landingcenter.add("Betapur(RRO)");
		landingcenter.add("Rangat Bay");
		landingcenter.add("KaushalyaNagar");
		landingcenter.add("Dashratpur");
		landingcenter.add("Yerrata");
		landingcenter.add("Long Island");
		landingcenter.add("Elphinstone Hr");
		landingcenter.add("Uttara");
		landingcenter.add("OralKatcha");
		landingcenter.add("Barren");
		landingcenter.add("Havelock");
		landingcenter.add("Middle Strait");
		landingcenter.add("ShoalBay");
		landingcenter.add("Wrightmyo");
		landingcenter.add("Neil Island");
		landingcenter.add("Port Blair");
		landingcenter.add("Bambooflat");
		landingcenter.add("Haddo");
		landingcenter.add("Hope Town");
		landingcenter.add("Dunduspoint");
		landingcenter.add("Phoenix Bay");
		landingcenter.add("Junglighat");
		landingcenter.add("Dignabad");
		landingcenter.add("Mt Haughton");
		landingcenter.add("Lohabarrack");
		landingcenter.add("Chouldari");
		landingcenter.add("Wandoor");
		landingcenter.add("Chidiyatapu");
		landingcenter.add("Rutland");
		landingcenter.add("Cinque Island");
		landingcenter.add("Tambe-e-bul");
		landingcenter.add("Vivekanandpur,LittleAndaman");
		landingcenter.add("RamaKrishnaPur");
		landingcenter.add("Kwate-tu-Kwage");
		landingcenter.add("Harminder Bay");
		landingcenter.add("Machidera(Hutbay)");
		landingcenter.add("Benyaboi");
		landingcenter.add("Tula");
		landingcenter.add("Tochangeou");
		landingcenter.add("Keating Pt (Car Nicobar)");
		landingcenter.add("Mus,CarNicobar");
		landingcenter.add("Sawai (Car Nicobar)");
		landingcenter.add("Teetop,CarNicobar");
		landingcenter.add("Passa,Car Nicobar");
		landingcenter.add("Arrong (Car Nicobar)");
		landingcenter.add("Malacca,CarNicobar");
		landingcenter.add("Batti Malv");
		landingcenter.add("Chowra");
		landingcenter.add("Aoang");
		landingcenter.add("Laksi");
		landingcenter.add("Bampoka");
		landingcenter.add("Kai-Hoa");
		landingcenter.add("Takaroach");
		landingcenter.add("Trinket,Nancowry");
		landingcenter.add("Kamorta,Nancowry");
		landingcenter.add("Hitui,Nancowry");
		landingcenter.add("Champion,Nancowry");
		landingcenter.add("Balubasti,Nancowry Island");
		landingcenter.add("Attabiak,Nancowry Island");
		landingcenter.add("Tapong,Nancowry Island");
		landingcenter.add("Cape Connaught");
		landingcenter.add("Kapanga,Katchall");
		landingcenter.add("Katchal East Bay");
		landingcenter.add("Jansin");
		landingcenter.add("Katchal West Bay");
		landingcenter.add("Sombrero Pt");
		landingcenter.add("Pulo Patia");
		landingcenter.add("Kabra Pt");
		landingcenter.add("Tenlaa");
		landingcenter.add("Rosen Pt");
		landingcenter.add("CampbellBay");
		landingcenter.add("Vijoy Nagar");
		landingcenter.add("Indira Pt");
		landingcenter.add("Kokeon");
		landingcenter.add("Pulo Kunji");
		landingcenter.add("Valiyapani reef");
		landingcenter.add("Byramgore");
		landingcenter.add("Cheriyapani reef");
		landingcenter.add("Chetlat I");
		landingcenter.add("Bitra I");
		landingcenter.add("Kiltani");
		landingcenter.add("Perumalpar reef");
		landingcenter.add("Kadmath I");
		landingcenter.add("Amini I");
		landingcenter.add("Tinnakara");
		landingcenter.add("Bangaram I");
		landingcenter.add("Agatti I");
		landingcenter.add("Androth I");
		landingcenter.add("Kavaratti I");
		landingcenter.add("Valiykara");
		landingcenter.add("Suheli");
		landingcenter.add("Cheriyakara");
		landingcenter.add("Kalpeni I");
		landingcenter.add("Minicoy​");
		return landingcenter;
	}






	public NavicFishLandingCenters() {
		super();
		states.add("Gujarat");
		states.add("Maharashtra");
		states.add("Goa");
		states.add("Karnataka");
		states.add("Kerala");
		states.add("SouthTamilNadu");
		states.add("NorthTamilNadu");
		states.add("SouthAndhraPradesh");
		states.add("NorthAndhraPradesh");
		states.add("Odisha");
		states.add("WestBengal");
		states.add("Andaman");
		states.add("Nicobar");
		states.add("Lakshadweep");
		states.add("EastCoast");
		states.add("WestCoast");
		states.add("ALLINDIA");

		LinkedHashMap<Integer, String> data = new LinkedHashMap<Integer, String>();
		data.put(1,"Lakhapat");
		data.put(2,"Kanoj");
		data.put(3,"Narayan Sarovar (Koteshwar)");
		data.put(4,"Guvar");
		data.put(5,"Lakhi Bandar");
		data.put(6,"Bhutau");
		data.put(7,"Moti Akri");
		data.put(8,"Mitha Port");
		data.put(9,"Jakhau");
		data.put(10,"Kadoli");
		data.put(11,"Khuada");
		data.put(12,"Chhachhi");
		data.put(13,"Bambhdai");
		data.put(14,"Bhada");
		data.put(15,"Nana Layja");
		data.put(16,"Kanthada");
		data.put(17,"Mandvi");
		data.put(18,"Rawal Pir Dargah");
		data.put(19,"Modhva");
		data.put(20,"Tragdi");
		data.put(21,"Tunda");
		data.put(22,"Navinal");
		data.put(23,"Zarpara");
		data.put(24,"Mundra");
		data.put(25,"Shekhadiya");
		data.put(26,"Luni");
		data.put(27,"Bhadreshwar");
		data.put(28,"Kukadsar");
		data.put(29,"Sanghad");
		data.put(30,"Tuna Port");
		data.put(31,"Tekra");
		data.put(32,"Kandla");
		data.put(33,"Navlakhi");
		data.put(34,"Dabar Cr");
		data.put(35,"Jodiya");
		data.put(36,"Balachadi");
		data.put(37,"Sachana");
		data.put(38,"Kalyan Lt");
		data.put(39,"Piroton Island");
		data.put(40,"Sikka");
		data.put(41,"Vadinar");
		data.put(42,"Bharana");
		data.put(43,"Nana Ambla");
		data.put(44,"Salaya");
		data.put(45,"Mota Asota");
		data.put(46,"Poshitra");
		data.put(47,"Okha");
		data.put(48,"Mitha Port");
		data.put(49,"Kachchigadh");
		data.put(50,"Rupen");
		data.put(51,"Dwarka");
		data.put(52,"Kuranga");
		data.put(53,"Bhogat");
		data.put(54,"Navadra");
		data.put(55,"Harshad Miyani");
		data.put(56,"Miyani");
		data.put(57,"Tukda Miyani");
		data.put(58,"Raatadi");
		data.put(59,"Kuchhadi");
		data.put(60,"Porbandar");
		data.put(61,"Odadar");
		data.put(62,"Navibandar");
		data.put(63,"Gorsar");
		data.put(64,"Madhavpur");
		data.put(65,"Shil");
		data.put(66,"Mangrol");
		data.put(67,"Mangrol Bara");
		data.put(68,"Chorwad");
		data.put(69,"Adri");
		data.put(70,"Veraval");
		data.put(71,"Hirakot");
		data.put(72,"Kadwar");
		data.put(73,"Sutrapada");
		data.put(74,"Vadodra");
		data.put(75,"Dhamlej");
		data.put(76,"Mul Dwarka");
		data.put(77,"Madhvad Lighthouse");
		data.put(78,"Kotda");
		data.put(79,"Diu Island");
		data.put(80,"Nava Bandar");
		data.put(81,"Simar");
		data.put(82,"Saiyad Rajpara");
		data.put(83,"Rohisha");
		data.put(84,"Jafarabad");
		data.put(85,"Shiyalbet");
		data.put(86,"Pipavav");
		data.put(87,"Patva");
		data.put(88,"Gadhada");
		data.put(89,"Mahuva (Bhavani Bandar)");
		data.put(90,"Mahuva (Light House)");
		data.put(91,"Nikol");
		data.put(92,"Methla");
		data.put(93,"Jhanjhmer");
		data.put(94,"Gopnath");
		data.put(95,"Sartanpar");
		data.put(96,"Alang");
		data.put(97,"Mithi Virdi");
		data.put(98,"Haathab");
		data.put(99,"Piram Bet");
		data.put(100,"Badi");
		data.put(101,"Ghogha");
		data.put(102,"Bhavanagar New Port");
		data.put(103,"Dungariya Bet");
		data.put(104,"Kamatalav");
		data.put(105,"Vadgam");
		data.put(106,"Khambat");
		data.put(107,"Surwada");
		data.put(108,"Sarod");
		data.put(109,"Kavi");
		data.put(110,"Gangeshwar");
		data.put(111,"Zamdi");
		data.put(112,"Nadiyad");
		data.put(113,"Tankari Pt");
		data.put(114,"Asharsha");
		data.put(115,"Denwa");
		data.put(116,"Luvara");
		data.put(117,"Mehgam");
		data.put(118,"Dhanturia");
		data.put(119,"Wansnoli");
		data.put(120,"Bhadbhut");
		data.put(121,"Oil Derrick");
		data.put(122,"Kanthiajal");
		data.put(123,"Kosamba (MangelVad)");
		data.put(124,"Karanj");
		data.put(125,"Mor");
		data.put(126,"Marphalia");
		data.put(127,"Gunav");
		data.put(128,"Bhagal");
		data.put(129,"Hazira");
		data.put(130,"Dumas");
		data.put(131,"Magadalla");
		data.put(132,"Bhimpur");
		data.put(133,"Dipla");
		data.put(134,"Wasi Borsi");
		data.put(135,"Dandi");
		data.put(136,"Onjal Machhivad");
		data.put(137,"Krishnapur");
		data.put(138,"Bhat");
		data.put(139,"Mendhar");
		data.put(140,"Dholai");
		data.put(141,"NaniDanti");
		data.put(142,"Kakwadi");
		data.put(143,"Bhadeli Jagalala");
		data.put(144,"Valsad");
		data.put(145,"Kosamba (Machhivad)");
		data.put(146,"Magod Dungri");
		data.put(147,"Umarsadi");
		data.put(148,"Kolak");
		data.put(149,"Bhimpor");
		data.put(150,"Daman");
		data.put(151,"Kalai");
		data.put(152,"Fansa");
		data.put(153,"Maroli");
		data.put(154,"Tadgam");
		data.put(155,"Kathalwada");
		data.put(156,"Nargol");
		data.put(157,"Umargam");
		landingcenters.add(0,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Zai");
		data.put(2,"Bordi");
		data.put(3,"Gholvad");
		data.put(4,"Narpad/DahanuAgar");
		data.put(5,"Dahanu");
		data.put(6,"Khondha Cr");
		data.put(7,"DhaktiDahanu/Gungawada");
		data.put(8,"Varor");
		data.put(9,"Kambode");
		data.put(10,"Ghivali");
		data.put(11,"Tarapur Pt");
		data.put(12,"PokharanDandi/Uchheli");
		data.put(13,"Navapur (Ucheli Cr)");
		data.put(14,"Murbe");
		data.put(15,"Satpati(N)");
		data.put(16,"Satpati(M/S)");
		data.put(17,"Satpati");
		data.put(18,"Shirgaon");
		data.put(19,"Vadarai");
		data.put(20,"Kelwane");
		data.put(21,"Kelwa/KelwaDadar");
		data.put(22,"Mahim Cr");
		data.put(23,"Danda");
		data.put(24,"Edavan/Kore");
		data.put(25,"Datiware");
		data.put(26,"Arnala");
		data.put(27,"Tembhi");
		data.put(28,"Arnalapada");
		data.put(29,"Rangaon");
		data.put(30,"MulgaonDanda");
		data.put(31,"Vasai(Pachubandar)");
		data.put(32,"Khochiwade");
		data.put(33,"Vasai");
		data.put(34,"Dongi Point");
		data.put(35,"Dongri");
		data.put(36,"Uttan");
		data.put(37,"Uttan(Bhatye)");
		data.put(38,"Gorai");
		data.put(39,"Manori");
		data.put(40,"Marve/Malvani");
		data.put(41,"YerangalBhati");
		data.put(42,"Madh");
		data.put(43,"Patwadi");
		data.put(44,"Vesava");
		data.put(45,"Varsova");
		data.put(46,"JuhumoraGaon");
		data.put(47,"JuhuTara");
		data.put(48,"KharDanda");
		data.put(49,"Uarashi Rf");
		data.put(50,"Chimbai");
		data.put(51,"Mahim");
		data.put(52,"Naigaon");
		data.put(53,"Worli");
		data.put(54,"Worli-Lotus");
		data.put(55,"Malabar Port (Mumbai)");
		data.put(56,"CuffPared");
		data.put(57,"Colaba Pt.(Mumbai)");
		data.put(58,"SasoonDock");
		data.put(59,"Kalbadevi");
		data.put(60,"Chinchbunder");
		data.put(61,"NewFerryWharf");
		data.put(62,"Trombay");
		data.put(63,"Mahul");
		data.put(64,"WashiBridge,PWDJetty");
		data.put(65,"Vashi(Haveli)");
		data.put(66,"Belapur");
		data.put(67,"UlwaMoha");
		data.put(68,"Morave-1");
		data.put(69,"Nhawa");
		data.put(70,"Dighode");
		data.put(71,"Mora");
		data.put(72,"HanumanKoliwada");
		data.put(73,"Uran");
		data.put(74,"Bhalpada");
		data.put(75,"Waredi");
		data.put(76,"Dharmtar Dhakka");
		data.put(77,"Revas");
		data.put(78,"Karanja Uran");
		data.put(79,"Sasawane");
		data.put(80,"Avas");
		data.put(81,"Navgaon");
		data.put(82,"Thal");
		data.put(83,"VarsoliChalmala");
		data.put(84,"Alibag");
		data.put(85,"Nagaon");
		data.put(86,"Theronda");
		data.put(87,"Rewdanda");
		data.put(88,"Boghar");
		data.put(89,"Salav");
		data.put(90,"Revadanda");
		data.put(91,"Korlai");
		data.put(92,"Borli-Mandla");
		data.put(93,"Mazgaon");
		data.put(94,"Ekdara");
		data.put(95,"Murud");
		data.put(96,"Rajpuri");
		data.put(97,"Agardanda");
		data.put(98,"Mandad");
		data.put(99,"Pabhare");
		data.put(100,"Kharsai");
		data.put(101,"Kudgaon");
		data.put(102,"Dighi(Savari)");
		data.put(103,"Nanwell Pt");
		data.put(104,"Bhardkhol-Diveagar");
		data.put(105,"Diveagar");
		data.put(106,"Shekhadi(Khalchi)");
		data.put(107,"Srivardhan");
		data.put(108,"Bagmandla");
		data.put(109,"Veshawi-Bankot");
		data.put(110,"Bankot");
		data.put(111,"Velas");
		data.put(112,"Kelshi");
		data.put(113,"Kelsi");
		data.put(114,"AadeUttambar");
		data.put(115,"Anjarle");
		data.put(116,"Paj");
		data.put(117,"HarnePort");
		data.put(118,"Harne");
		data.put(119,"Murud");
		data.put(120,"Burondi");
		data.put(121,"Kolthare");
		data.put(122,"Dabhol");
		data.put(123,"Veldur/Navanagar/Dhopave");
		data.put(124,"Tolkeshwar Pt");
		data.put(125,"Anjanvel");
		data.put(126,"Guhagar");
		data.put(127,"Asgoli");
		data.put(128,"Sakhar-Hedvi");
		data.put(129,"Palshet");
		data.put(130,"Budhal");
		data.put(131,"Kondkarul");
		data.put(132,"Welneshwar");
		data.put(133,"Hedvi");
		data.put(134,"Jaigad");
		data.put(135,"SakharJaigad");
		data.put(136,"Jaigarh Head");
		data.put(137,"Varawade");
		data.put(138,"Kharviwada");
		data.put(139,"MTDC");
		data.put(140,"Kalabadevi");
		data.put(141,"SakhartarKasarveli");
		data.put(142,"JakiMirya");
		data.put(143,"Mirkarwada");
		data.put(144,"Ratnagiri");
		data.put(145,"Rajiwada");
		data.put(146,"Rajiwada-Kerla");
		data.put(147,"Someshvar");
		data.put(148,"Phansop");
		data.put(149,"Golap-Pawas");
		data.put(150,"Purnagad");
		data.put(151,"Purangad");
		data.put(152,"Sakhri-Natye");
		data.put(153,"Mavlanga");
		data.put(154,"Ambere");
		data.put(155,"Bokarwadi");
		data.put(156,"Wada Vetye");
		data.put(157,"Sakharinate");
		data.put(158,"Ambolgad");
		data.put(159,"Ambolgarh");
		data.put(160,"PhansePadawane");
		data.put(161,"Padve");
		data.put(162,"Sakhar-Akshi");
		data.put(163,"Wagapur Pt");
		data.put(164,"Jambhari");
		data.put(165,"Vijayadurg Hr");
		data.put(166,"Vijaydurg");
		data.put(167,"Kalamaiwadi");
		data.put(168,"Wadatar/Malai");
		data.put(169,"Anandwadi(Devgad)");
		data.put(170,"Devgarh");
		data.put(171,"Mithmumbri/Taramumbari");
		data.put(172,"Kunkeshwar");
		data.put(173,"Kunkeshwar/Katvan");
		data.put(174,"Mithbao");
		data.put(175,"Munge");
		data.put(176,"Achra Pt");
		data.put(177,"Achara");
		data.put(178,"Tondavli");
		data.put(179,"Hadi");
		data.put(180,"Sarjekot-MiryaBandh");
		data.put(181,"Talashil");
		data.put(182,"Sarjekot");
		data.put(183,"Dhurivada");
		data.put(184,"Sindhudurg (Malvan)");
		data.put(185,"Wayri");
		data.put(186,"Tarkarli/Kalethar");
		data.put(187,"Deobag");
		data.put(188,"Kochara-Nivati");
		data.put(189,"Khavana");
		data.put(190,"Kelus");
		data.put(191,"Mobar-Bhogave");
		data.put(192,"Khanoli-Wayangani");
		data.put(194,"Dabhoswada/Navabag");
		data.put(195,"MuthUbhadanda");
		data.put(196,"Mochemad");
		data.put(197,"Shiroda");
		data.put(198,"Redi");
		data.put(199,"Terekhol");
		landingcenters.add(1,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Chapora");
		data.put(2,"Aguada");
		data.put(3,"Panaji (Malim)");
		data.put(4,"Santerem Pt (Vasco)");
		data.put(5,"Majorde");
		data.put(6,"Fatarde");
		data.put(7,"Betul");
		data.put(8,"Cutbona");
		data.put(9,"Talpona");
		data.put(10,"Kolamb");
		data.put(11,"Vengurla");
		landingcenters.add(2,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Majali");
		data.put(2,"Sadasguvgarg");
		data.put(3,"Karwar");
		data.put(4,"Belekeri");
		data.put(5,"Gangavali");
		data.put(6,"Tadri");
		data.put(7,"Kumta Pt");
		data.put(8,"Dhareshvar");
		data.put(9,"Karki");
		data.put(10,"Honavar");
		data.put(11,"Kasarkod");
		data.put(12,"Navayatkere");
		data.put(13,"Mavalli");
		data.put(14,"Shirali");
		data.put(15,"Bhatkal");
		data.put(16,"Baindur");
		data.put(17,"Navunda");
		data.put(18,"Gangoli");
		data.put(19,"Coondapoor (gangoli)");
		data.put(20,"Kota");
		data.put(21,"Hangarkatta");
		data.put(22,"Malpe");
		data.put(23,"Udiyavara");
		data.put(24,"Kapu");
		data.put(25,"Mulki");
		data.put(26,"Hosabettu-Udaivar");
		data.put(27,"Suratakal Pt");
		data.put(28,"New Mangalore");
		data.put(29,"Mangalore");
		landingcenters.add(3,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Kunzhathur");
		data.put(2,"Manjeshwara");
		data.put(3,"Uppala");
		data.put(4,"Arikkadi");
		data.put(5,"Kumbla");
		data.put(6,"Koipadi");
		data.put(7,"Mogral");
		data.put(8,"Adakathbail");
		data.put(9,"Kasaragod");
		data.put(10,"ThalangarJetty");
		data.put(11,"Kotikulam");
		data.put(12,"Bekal");
		data.put(13,"Pallikere");
		data.put(14,"Chittari");
		data.put(15,"Ajanoor-N-Bella");
		data.put(16,"Hosdrug");
		data.put(17,"Nileswaram");
		data.put(18,"Thaikadappuram");
		data.put(19,"BadagaraAzhithala");
		data.put(20,"CheruvathurFH");
		data.put(21,"Maniyat");
		data.put(22,"Kavvayi");
		data.put(23,"Kunnariyam");
		data.put(24,"Ettikulam");
		data.put(25,"Kotte Kunnu");
		data.put(26,"Koloth");
		data.put(27,"Azhikal");
		data.put(28,"Valapattanam");
		data.put(29,"Azheecode");
		data.put(30,"AzheecodeSouth");
		data.put(31,"Kannur");
		data.put(32,"AyikkaraFH");
		data.put(33,"Edakkad");
		data.put(34,"Muzhuppilangad");
		data.put(35,"Tellicherry");
		data.put(36,"NewMahe");
		data.put(37,"Mahe");
		data.put(38,"ChombalaFH");
		data.put(39,"Uralungal");
		data.put(40,"Nalliyankara");
		data.put(41,"Badagara");
		data.put(42,"Puduppanam");
		data.put(43,"Kottakkal");
		data.put(44,"Kizhur");
		data.put(45,"Tikkoti");
		data.put(46,"Moodady");
		data.put(47,"Thikkodi(Kodikkal)");
		data.put(48,"Kadalur Pt");
		data.put(49,"Quilandy/Koloth(Defunct)");
		data.put(50,"Kollam");
		data.put(51,"Poilkavu");
		data.put(52,"Chemancheri");
		data.put(53,"Kappad");
		data.put(54,"Elathur");
		data.put(55,"Elattur");
		data.put(56,"PuthiyappaFH");
		data.put(57,"Puthengadi/Paravanna");
		data.put(58,"Kunduparabu");
		data.put(59,"Nadakkavu");
		data.put(60,"Vellayil");
		data.put(61,"Calicut");
		data.put(62,"VadakkeKadappuram");
		data.put(63,"BeyporeFH");
		data.put(64,"Ramanattukara");
		data.put(65,"Chaliyam");
		data.put(66,"Beypore");
		data.put(67,"Kadalundinagaram");
		data.put(68,"Parapanangadi");
		data.put(69,"Parappanangadi");
		data.put(70,"Thanur");
		data.put(71,"Tanur Nagaram");
		data.put(72,"Paravannangadi");
		data.put(73,"Vakkad");
		data.put(74,"Koottayi");
		data.put(75,"Purattur");
		data.put(76,"Ponnani");
		data.put(77,"Veliyangod");
		data.put(78,"Palappetty");
		data.put(79,"Attupuram");
		data.put(80,"Mannalamkunnu");
		data.put(81,"Vayilattur");
		data.put(82,"Panchavadi");
		data.put(83,"Edakazhiyur");
		data.put(84,"Blangad");
		data.put(85,"Chavakkad");
		data.put(86,"Mullassheri");
		data.put(87,"Vadanappally");
		data.put(88,"Thalikulam");
		data.put(89,"Nattika");
		data.put(90,"Kazhimbram");
		data.put(91,"Edamuttam");
		data.put(92,"Palapetty");
		data.put(93,"KaipamangalamVanchipura");
		data.put(94,"PerinjanamAraattukadavu");
		data.put(95,"Kulimuttam");
		data.put(96,"Kara");
		data.put(97,"Pullut");
		data.put(98,"Eriyad(Chelarappa)");
		data.put(99,"Kodungallur");
		data.put(100,"MunambamFH");
		data.put(101,"Munambam");
		data.put(102,"Manakodam");
		data.put(103,"Kuzhuppilly");
		data.put(104,"Cherai");
		data.put(105,"Edvankad");
		data.put(106,"Edavanakad");
		data.put(107,"Vadakkal");
		data.put(108,"Puthenkadappuram");
		data.put(109,"Narakkal");
		data.put(110,"Nayarambalam");
		data.put(111,"Malipuram");
		data.put(112,"Ernakulam");
		data.put(113,"Murikumpadam");
		data.put(114,"Kalamukku");
		data.put(115,"Vypeen");
		data.put(116,"Valarpadam");
		data.put(117,"FortKochi");
		data.put(118,"Kochi");
		data.put(119,"Chillickal");
		data.put(120,"Puthenthodu(Kannamali)");
		data.put(121,"Maruvakad");
		data.put(122,"Chellanum");
		data.put(123,"Pallithodu");
		data.put(124,"Palithodu");
		data.put(125,"Manakkodam");
		data.put(126,"Thykal");
		data.put(127,"Arthunkal/Chennavely");
		data.put(128,"Aratungal");
		data.put(129,"Chethy");
		data.put(130,"Kottamkulangara");
		data.put(131,"Pollethai");
		data.put(132,"Thumpolly");
		data.put(133,"Thazhampally");
		data.put(134,"Alleppey");
		data.put(135,"AlleppeyBeach");
		data.put(136,"Kalarkod");
		data.put(137,"Punnappra");
		data.put(138,"Punnappira");
		data.put(139,"Valanjavazhy");
		data.put(140,"Ambalapuzha");
		data.put(141,"Purakkad");
		data.put(142,"Porakad");
		data.put(143,"Thottappally");
		data.put(144,"Thrikunnapuzha");
		data.put(145,"Trikkunnapuzha");
		data.put(146,"Padiyamkara Tekku");
		data.put(147,"Ramancheri Tura");
		data.put(148,"AzheekalJetty");
		data.put(149,"Alappattu");
		data.put(150,"Cheriazheekal");
		data.put(151,"Kovilthottam");
		data.put(152,"Chavara");
		data.put(153,"Puthenthura");
		data.put(154,"Vettuthura");
		data.put(155,"Neendakara");
		data.put(156,"Sakthikulangara");
		data.put(157,"Thankassery F.H.");
		data.put(158,"QuilonPort");
		data.put(159,"Quilon");
		data.put(160,"Wadi");
		data.put(161,"Moothakara");
		data.put(162,"Pallithottam");
		data.put(163,"Eravipuram");
		data.put(164,"Tanni");
		data.put(165,"Pozhikkara");
		data.put(166,"Pozhikara");
		data.put(167,"Paravoor");
		data.put(168,"Edava");
		data.put(169,"Kappil");
		data.put(170,"Edaval");
		data.put(171,"Vettoor");
		data.put(172,"Vettur");
		data.put(173,"Chilakkoor");
		data.put(174,"Arivalam&Rathikkal");
		data.put(175,"Mampally");
		data.put(176,"AnjengoNorth");
		data.put(177,"Anjengo");
		data.put(178,"AnjengoSouth");
		data.put(179,"Poothura");
		data.put(180,"Perumathura");
		data.put(181,"Perumatura");
		data.put(182,"Puthukurichi");
		data.put(183,"Puthenthoppu");
		data.put(184,"St.Andrews");
		data.put(185,"Pallithura");
		data.put(186,"Thumba");
		data.put(187,"Valiaveli");
		data.put(188,"Kochuveli");
		data.put(189,"Vell");
		data.put(190,"Vettucaud");
		data.put(191,"Vettucaud");
		data.put(192,"Kannanthura");
		data.put(193,"Kochuthoppu");
		data.put(194,"Trivandrum");
		data.put(195,"Valiathura/ValiathuraPier");
		data.put(196,"Cheriathura");
		data.put(197,"Bheemapally");
		data.put(198,"Poonthura");
		data.put(199,"Tiruvallam");
		data.put(200,"PanathuraSouth");
		data.put(201,"Kovalad");
		data.put(202,"Vizhinjam&Kottapuram");
		data.put(203,"Vilinjam");
		data.put(204,"VizhinjamNorth");
		data.put(205,"Mariyanadu");
		data.put(206,"Adimalathura");
		data.put(207,"Puthiathura(Kochupally)");
		data.put(208,"Karichal");
		data.put(209,"Puthiathura(Chinnamarthandanthura)");
		data.put(210,"Kochuthura");
		data.put(211,"Poovar");
		data.put(212,"Puvar");
		data.put(213,"Pozhiyoor");
		landingcenters.add(4,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Neerodi");
		data.put(2,"Marthandamthurai");
		data.put(3,"Vallavilai");
		data.put(4,"Eraviputhenthurai");
		data.put(5,"Ezhudesam Chinnathurai");
		data.put(6,"Thoothur");
		data.put(7,"Poothurai");
		data.put(8,"Erayammanthura");
		data.put(9,"Erayumanthurai");
		data.put(10,"Thengapattanam");
		data.put(11,"Mulloorthurai");
		data.put(12,"Ramanthurai");
		data.put(13,"Enayam puthenthurai");
		data.put(14,"Enayam Chinnathurai");
		data.put(15,"Enayam");
		data.put(16,"Midaalam");
		data.put(17,"Midalam (Naduthurai");
		data.put(18,"Kurumbanai");
		data.put(19,"Vaniyakudi");
		data.put(20,"Kodimunai");
		data.put(21,"Simon colony");
		data.put(22,"Coalchel");
		data.put(23,"Kottilpadu");
		data.put(24,"Mandaikadu puthoor");
		data.put(25,"Periavilai");
		data.put(26,"Chinnavilai");
		data.put(27,"Melakadiapattinam");
		data.put(28,"Kovalam");
		data.put(29,"Keezhakadiapattinam");
		data.put(30,"Melamuttom");
		data.put(31,"Muttom");
		data.put(32,"Azhikkal");
		data.put(33,"Rajakkamanglam");
		data.put(34,"Rajakamangalam Thurai");
		data.put(35,"Periyakadu");
		data.put(36,"Pozhikkarai");
		data.put(37,"Kesavanputhenthurai");
		data.put(38,"Puthenthurai");
		data.put(39,"Pallam");
		data.put(40,"Keezhamanakudi");
		data.put(41,"Mela Manakudi");
		data.put(42,"Kovalam Kanniyakumarai");
		data.put(43,"Puthur");
		data.put(44,"Puthugramam (Vavuthurai");
		data.put(45,"Kanniyakumari");
		data.put(46,"Chinnamuttom");
		data.put(47,"Lipuram");
		data.put(48,"Arockiyapuram");
		data.put(49,"Kuttapuli");
		data.put(50,"Chettikulam");
		data.put(51,"Perumanal");
		data.put(52,"Kudangulam");
		data.put(53,"Idinthakarai");
		data.put(54,"Perumanal");
		data.put(55,"Thommayarpuram(Muddukuli");
		data.put(56,"Koothanguzhi");
		data.put(57,"Kundal");
		data.put(58,"Uvari");
		data.put(59,"Koottappanai");
		data.put(60,"Kooduthalai");
		data.put(61,"Periyathalai");
		data.put(62,"Manappad Pt");
		data.put(63,"Kulasekharapattinam");
		data.put(64,"Kallamozhi");
		data.put(65,"Alanthalai");
		data.put(66,"Amalinagar");
		data.put(67,"Jeevanagar");
		data.put(68,"Veerapandiyapattinam");
		data.put(69,"Singhithurai");
		data.put(70,"Kombuthurai Madhakoil");
		data.put(71,"Punnakkayal");
		data.put(72,"Ratchanyapuram");
		data.put(73,"Tuticorin");
		data.put(74,"Pandyan");
		data.put(75,"Inico nagar");
		data.put(76,"Thoothukudi");
		data.put(77,"Therespuram");
		data.put(78,"Thalamuthunagar");
		data.put(79,"Vellapatti");
		data.put(80,"Tharuvaikulam");
		data.put(81,"Pattanamarudur");
		data.put(82,"Veppalodai");
		data.put(83,"Sippikulam");
		data.put(84,"Keezhavaippar");
		data.put(85,"Periasamypuram");
		data.put(86,"Vembar");
		data.put(87,"Rojma Nagar");
		data.put(88,"Terku Mookkaiyur");
		data.put(89,"Valinokkam");
		data.put(90,"Chinna Ervadi");
		data.put(91,"Kilakarai");
		data.put(92,"Kalimankundu");
		data.put(93,"Muttupettai");
		data.put(94,"Inthira Nagar");
		data.put(95,"Valangapuri");
		data.put(96,"Seeniyappa Dharga");
		data.put(97,"Vedhalai");
		data.put(98,"Mandapam (South)");
		data.put(99,"Chinnapalam");
		data.put(100,"Pamban Kunthukal");
		data.put(101,"Mukuntharayarchatram");
		data.put(102,"Dhanushkodi");
		data.put(103,"Verkode");
		data.put(104,"Rameshwaram Harbour");
		data.put(105,"Olaikuda");
		data.put(106,"Villundi");
		data.put(107,"Thangachimadam");
		data.put(108,"Pamban Light House");
		data.put(109,"Mandpam (North)");
		data.put(110,"Munaikadu");
		data.put(111,"Atrangarai");
		data.put(112,"Alagankulam");
		data.put(113,"Pudukkudi");
		data.put(114,"Panaikulam");
		data.put(115,"Pudhuvalasaichathiram");
		data.put(116,"Palanivalasai");
		data.put(117,"Mudiveeranpattinam");
		data.put(118,"Devipattinam South");
		data.put(119,"Devipattinam");
		data.put(120,"Pathanendal");
		data.put(121,"Thirupalaikudi North");
		data.put(122,"Moreppanai");
		data.put(123,"Karankadu");
		data.put(124,"Mullimanai");
		data.put(125,"Pudhupattinam");
		data.put(126,"Tiruvettriyur");
		data.put(127,"Soliyakudi Harbour");
		data.put(128,"Nambuthalai");
		data.put(129,"Tondi");
		data.put(130,"M.R.Pattinam");
		data.put(131,"Valasapatinam(P.V.Pattinam");
		data.put(132,"Narendhal");
		data.put(133,"Dhamotharanpattinam");
		data.put(134,"Pasipattinam");
		data.put(135,"Theerthaandathanam");
		data.put(136,"Sundarapandiyanpatta");
		data.put(137,"Muthukuda");
		data.put(138,"R.Pudhupattinam");
		data.put(139,"Gopalapattinam");
		data.put(140,"Muthanenthal");
		data.put(141,"Ayyampattinam");
		data.put(142,"Kottaippattanam");
		data.put(143,"Pudhukkudi South");
		data.put(144,"Pudhukkudi North");
		data.put(145,"Anthoniyarpuram");
		data.put(146,"Ponagaram");
		data.put(147,"Manamelkudi");
		data.put(148,"Keelakudiyiruppu");
		data.put(149,"Vadakku Amapattinam");
		data.put(150,"Seetharampattinam");
		landingcenters.add(5,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Krishnajipattinam");
		data.put(2,"Prathaparamanpattinam");
		data.put(3,"Kattumavadi");
		data.put(4,"Sembiyanmadevipattinam");
		data.put(5,"Ganesapuram");
		data.put(6,"Vallavanpattinam");
		data.put(7,"Subbamachatram");
		data.put(8,"Somanathanpattinam");
		data.put(9,"Annanagar Pudhutheru");
		data.put(10,"Mandhiripattinam");
		data.put(11,"Senthalaivayal");
		data.put(12,"Adaikkadevan");
		data.put(13,"Sambaipattinam");
		data.put(14,"Karanguda");
		data.put(15,"Kazhumanguda");
		data.put(16,"Sethubavachattram");
		data.put(17,"Pillayarthidal");
		data.put(18,"Chinnamanai");
		data.put(19,"Mallipattinam");
		data.put(20,"Puthupattinam");
		data.put(21,"Velivayal");
		data.put(22,"Kollukadu");
		data.put(23,"Keelathottam");
		data.put(24,"Eripurakkarai");
		data.put(25,"Gandhinagar");
		data.put(26,"Karaiyurtheru");
		data.put(27,"Maravakadu");
		data.put(28,"Thambikottai");
		data.put(29,"Muthupet");
		data.put(30,"Point Calimer");
		data.put(31,"Kodiyakarai");
		data.put(32,"Vedaranniyam");
		data.put(33,"Arkkattuthurai");
		data.put(34,"Topputturai");
		data.put(35,"Pushpavanam");
		data.put(36,"Kallinodu");
		data.put(37,"Vellapallam");
		data.put(38,"Vanavanmadevi");
		data.put(39,"Vettaikaranrippu");
		data.put(40,"Vilunthamavadi");
		data.put(41,"Kameshwaram");
		data.put(42,"Seruthur");
		data.put(43,"Velanganni");
		data.put(44,"Akkaraipettai");
		data.put(45,"Nagapattinam Harbour");
		data.put(46,"Nambiyar Nagar");
		data.put(47,"Samanthanpettai");
		data.put(48,"Nagore");
		data.put(49,"Karikal");
		data.put(50,"Pattinacherry");
		data.put(51,"Chinnorpettai");
		data.put(52,"Chandrappadi");
		data.put(53,"Tharangampadi");
		data.put(54,"Kuttiyandiyur");
		data.put(55,"Bommayanpettai (Vellakoil");
		data.put(56,"Perumalpettai");
		data.put(57,"Tranquebar");
		data.put(58,"Pudhupettai");
		data.put(59,"Thalampettai");
		data.put(60,"Chinnangudi");
		data.put(61,"Kaverippattinam");
		data.put(62,"Vanagiri");
		data.put(63,"Poombuhar");
		data.put(64,"Pudukuppam");
		data.put(65,"Madathukuppam");
		data.put(66,"Naickerkuppam");
		data.put(67,"Chavadikuppam");
		data.put(68,"Keezhamoovarkarai");
		data.put(69,"Tirumullaivasal");
		data.put(70,"Thoduvai");
		data.put(71,"Mudasalodai Village");
		data.put(72,"Koozhayar");
		data.put(73,"Kottaimedu");
		data.put(74,"Madavamedu");
		data.put(75,"Pazhayar");
		data.put(76,"Killai");
		data.put(77,"M.G.R. Thittu");
		data.put(78,"Mudasalodai");
		data.put(79,"Parangipettai");
		data.put(80,"Portonovo");
		data.put(81,"C Pudupettai");
		data.put(82,"Pudukuppam");
		data.put(83,"Veerampatinam");
		data.put(84,"Samanthapettai");
		data.put(85,"Samiyarpettai");
		data.put(86,"Kumarapettai");
		data.put(87,"Periyakuppam");
		data.put(88,"Chithiraipettai");
		data.put(89,"Rajappettai");
		data.put(90,"Sothikuppam");
		data.put(91,"Cuddalore Harbour");
		data.put(92,"Sonaankuppam");
		data.put(93,"Devanampattinam");
		data.put(94,"Thazhanguda");
		data.put(95,"Moorthipudukuppam");
		data.put(96,"Panithittu");
		data.put(97,"Narambai");
		data.put(98,"Nallavadu");
		data.put(99,"P. Pudukuppam");
		data.put(100,"Chinna Veerampattinam");
		data.put(101,"Veerampattinam");
		data.put(102,"Thengaithittu");
		data.put(103,"Pondicherry");
		data.put(104,"Vaithikuppam");
		data.put(105,"Solainagar North");
		data.put(106,"Sodhanaikuppam");
		data.put(107,"Nadukuppam");
		data.put(108,"Thandhirayankuppam");
		data.put(109,"Chinna mudaliarchavadi");
		data.put(110,"Bommaiyarpalyam");
		data.put(111,"Pillaichavadi");
		data.put(112,"Periya Kalapet");
		data.put(113,"Ganapathichettikulam");
		data.put(114,"Pudhukuppam");
		data.put(115,"Anichankuppam");
		data.put(116,"Mudaliarkuppam");
		data.put(117,"Nochikuppam");
		data.put(118,"Koonimedu Kuppam");
		data.put(119,"Chettinagar");
		data.put(120,"Anumandhaikuppam");
		data.put(121,"Komuttichavadikuppam");
		data.put(122,"Mandavai Pudukuppam");
		data.put(123,"Ekkiyarkuppam");
		data.put(124,"Marakkanam");
		data.put(125,"Kaippanikuppam");
		data.put(126,"Vasavankuppam");
		data.put(127,"Muttukaduazhagankuppam");
		data.put(128,"Alambaraikuppam");
		data.put(129,"Kadappakam");
		data.put(130,"Panaiyur Periya Kuppam");
		data.put(131,"Panaiyur Chinnakuppam");
		data.put(132,"Mudaliyar Kuppam");
		data.put(133,"Cheyyur");
		data.put(134,"Paramankeni");
		data.put(135,"Perun Thuravu Kuppam");
		data.put(136,"Pudhunadukuppam");
		data.put(137,"Pazhayanadukuppam");
		data.put(138,"Angalamman Kuppam");
		data.put(139,"Kadalore Ali Kuppam");
		data.put(140,"Padalore Periya Kuppam");
		data.put(141,"Kadalore Chinna Kuppam");
		data.put(142,"Uyyalikuppam");
		data.put(143,"Sadras");
		data.put(144,"Pudupattinam");
		data.put(145,"Sathurangapattinam");
		data.put(146,"Umarikuppam");
		data.put(147,"Meyyurkuppam");
		data.put(148,"Kokilamedu");
		data.put(149,"Venpursham");
		data.put(150,"Mamallapuram");
		data.put(151,"Mahabalipuram");
		data.put(152,"Devaneri");
		data.put(153,"Salavankuppam");
		data.put(154,"Pudu Nemeli Kuppam");
		data.put(155,"Pattipulam");
		data.put(156,"Soolerikattukuppam");
		data.put(157,"Nemmelikuppam");
		data.put(158,"Pudhukalpakkam");
		data.put(159,"Chemacherry");
		data.put(160,"Covelong (Kovalam)");
		data.put(161,"Egattur Karikattukuppam");
		data.put(162,"Kanathur Reddy Kuppam");
		data.put(163,"Kanathur");
		data.put(164,"Nainarkuppam");
		data.put(165,"Panaiyurkuppam");
		data.put(166,"Injampakkam");
		data.put(167,"Chinnandikuppam");
		data.put(168,"Periya Neelankarai");
		data.put(169,"Chinna Neelankarai");
		data.put(170,"Palavakkam");
		data.put(171,"Kottivakkam");
		data.put(172,"Thiruvanmiyur");
		data.put(173,"Odaikuppam");
		data.put(174,"Orurkuppam");
		data.put(175,"Srinivasapuram");
		data.put(176,"Mullimanagar");
		data.put(177,"Pattinampakkam");
		data.put(178,"Nochikuppam");
		data.put(179,"Cathedral (Chennai)");
		data.put(180,"Nadukuppam");
		data.put(181,"Ayothikuppam");
		data.put(182,"Mattankuppam");
		data.put(183,"Chennai");
		data.put(184,"Lakshmipuram Odaikuppam");
		data.put(185,"Royapuram");
		data.put(186,"Ondikuppam");
		data.put(187,"Nallathanneer Odaikuppam");
		data.put(188,"Thiruchinnankuppam");
		data.put(189,"Kasiviswanathar koil Kuppam");
		data.put(190,"Palagaithottikuppam");
		data.put(191,"Kasikoilkuppam");
		data.put(192,"Ernavoorkuppam");
		data.put(193,"Kathivakkam Chinnakuppam");
		data.put(194,"Kathivakkam Periakuppam");
		data.put(195,"Thazankuppam");
		data.put(196,"Ennore Mugathuvarakuppan");
		data.put(197,"Ennorekuppam");
		data.put(198,"Pulicat");
		data.put(199,"Coromandel");
		landingcenters.add(6,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Annamalaichery");
		data.put(2,"Periyamangodu");
		data.put(3,"Arambakkam");
		data.put(4,"Pulinjerikuppam");
		data.put(5,"Durgarajupatnam");
		data.put(6,"Kondur");
		data.put(7,"Arkatapalem");
		data.put(8,"Kottapatnam");
		data.put(9,"Tammenapatnam");
		data.put(10,"Krishnapatnam(Upputeru)");
		data.put(11,"Krishnapatnam");
		data.put(12,"Pathapalem");
		data.put(13,"Maipadu");
		data.put(14,"Pattapupalem");
		data.put(15,"Utukuru");
		data.put(16,"Isakapalle");
		data.put(17,"Zuvvaladinne");
		data.put(18,"Vatturupallepalem");
		data.put(19,"Ramayapatnam");
		data.put(20,"Chakicherla");
		data.put(21,"Itamukkala");
		data.put(22,"Allurukottapatnam");
		data.put(23,"Adavipallipalem");
		data.put(24,"Vetapalem");
		data.put(25,"Vadarevu");
		data.put(26,"Bestapalam Bapatla");
		data.put(27,"Suryalanka");
		data.put(28,"Nizampatnam");
		data.put(29,"Nachugunta");
		data.put(30,"Etimoga");
		data.put(31,"Sorlagondi");
		data.put(32,"Palakayatippa");
		data.put(33,"Machilipatnam");
		data.put(34,"Giripuram");
		data.put(35,"Pedda Gollapalem");
		data.put(36,"Antarvedi");
		data.put(37,"Narasapur Pt");
		data.put(38,"Bandamurlanka");
		data.put(39,"Odalarevu");
		landingcenters.add(7,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Kothapalem LH");
		data.put(2,"Bhairavapalem");
		data.put(3,"Kakinada");
		data.put(4,"Vakalapudi");
		data.put(5,"Uppada");
		data.put(6,"Konapapeta");
		data.put(7,"Perumallapuram");
		data.put(8,"Palmanpeta");
		data.put(9,"Danavaipeta");
		data.put(10,"Pentakota");
		data.put(11,"Revu Polavaram");
		data.put(12,"Rambilli");
		data.put(13,"Pudimadaka");
		data.put(14,"Visakhapatnam");
		data.put(15,"Bhimunipatnam");
		data.put(16,"Mukkam");
		data.put(17,"Konada");
		data.put(18,"Chintapalli");
		data.put(19,"Ramachandrapuram");
		data.put(20,"Allivalasa");
		data.put(21,"Kuppili");
		data.put(22,"Srikurmam");
		data.put(23,"Bandaruvanipeta");
		data.put(24,"Kalingapatnam");
		data.put(25,"Guppidipeta");
		data.put(26,"Jagannadhapuram");
		data.put(27,"Maruvada");
		data.put(28,"Kotta Naupada");
		data.put(29,"Bavanapadu");
		data.put(30,"Nuvvalarevu");
		data.put(31,"Metturu");
		data.put(32,"Ganguvada");
		data.put(33,"Baruva");
		data.put(34,"Iduvanipalem");
		data.put(35,"Kaviti");
		data.put(36,"Anantaraipur");
		data.put(37,"KeutaSonapur");
		data.put(38,"PatiSonapur");
		data.put(39,"Sonnapurampeta");
		landingcenters.add(8,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Rameyapatna");
		data.put(2,"Ekasingi");
		data.put(3,"Markondi");
		data.put(4,"New Golabandha");
		data.put(5,"Gopalpur-IFH");
		data.put(6,"Golabandha");
		data.put(7,"OldBuxipetta");
		data.put(8,"NewBaxipalli");
		data.put(9,"Gopalpur");
		data.put(10,"Garyampetta");
		data.put(11,"Sana Aryapalli");
		data.put(12,"BadaNuagaon");
		data.put(13,"SanaNuagaon");
		data.put(14,"Ganjam");
		data.put(15,"Kantiagada(Podampeta)");
		data.put(16,"Prayagi");
		data.put(17,"Ramalanka");
		data.put(18,"Bajarkot");
		data.put(19,"Khirisahi");
		data.put(20,"Satpara");
		data.put(21,"Siandi");
		data.put(22,"Arakhakud");
		data.put(23,"PuriNorth");
		data.put(24,"PuriSouth");
		data.put(25,"Puri");
		data.put(26,"Penthakata");
		data.put(27,"Bangor");
		data.put(28,"Chandrabhaga");
		data.put(29,"Kajalpatia(Khandiapatna)");
		data.put(30,"Tondahar");
		data.put(31,"Anakona&Dalukani");
		data.put(32,"Astaranga");
		data.put(33,"Balipantala");
		data.put(34,"Sudhikeswar(Talia)");
		data.put(35,"NuagarhFH(Astaranga)");
		data.put(36,"Nuagar");
		data.put(37,"Bandar");
		data.put(38,"Magarkhia");
		data.put(39,"Saharabedi");
		data.put(40,"Kaliakana");
		data.put(41,"Noliasahi");
		data.put(42,"Nuagan");
		data.put(43,"Jamuka");
		data.put(44,"ParadeepFH");
		data.put(45,"Paradip");
		data.put(46,"Atharabanki");
		data.put(47,"Chumuhani");
		data.put(48,"Kharnasi");
		data.put(49,"False Point");
		data.put(50,"Kharinasi");
		data.put(51,"Jambu");
		data.put(52,"Jmboo");
		data.put(53,"Barunie");
		data.put(54,"Sasanpeta(Tantiapal)");
		data.put(55,"Gajarajpur");
		data.put(56,"Hariharpur");
		data.put(57,"Satbhaya");
		data.put(58,"Ahirajpur");
		data.put(59,"Talchua");
		data.put(60,"Dhamra");
		data.put(61,"Chandinipal");
		data.put(62,"DhamaraFH");
		data.put(63,"Kaithakhola");
		data.put(64,"Karanjamal");
		data.put(65,"Baincha");
		data.put(66,"Karanpalli");
		data.put(67,"Kasianala");
		data.put(68,"ChudamaniBoatJetty");
		data.put(69,"Chudamani");
		data.put(70,"Panchubisa");
		data.put(71,"Godaisagar");
		data.put(72,"Janipur");
		data.put(73,"Mahisali");
		data.put(74,"Chandipur");
		data.put(75,"Balaramgadi(ChandipurFLC)");
		data.put(76,"Balaramgadi");
		data.put(77,"Bahabalapur(KasafalSouth)");
		data.put(78,"Bahabalpur");
		data.put(79,"Bindha");
		data.put(80,"Hansakura");
		data.put(81,"Kasafala");
		data.put(82,"Choumukh");
		data.put(83,"Dagara");
		data.put(84,"Kirtania");
		data.put(85,"Chandeneswar");
		data.put(86,"Talasari");
		landingcenters.add(9,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"DighaMohanaF.F.T.A.(Digha)");
		data.put(2,"Shankarpur");
		data.put(3,"SankarpurF.F.T.A.(Sankarpur)");
		data.put(4,"TajpurJaldha");
		data.put(5,"Digha");
		data.put(6,"Junput");
		data.put(7,"Petuaghat (Dariapur)");
		data.put(8,"LightHouse,GangasagarGP");
		data.put(9,"Diamond Harbour Jettty Ghat in front of SDO, Office");
		data.put(10,"Diamond Harbour");
		data.put(11,"Kakdwip");
		data.put(12,"Namkhana");
		data.put(13,"Sagar");
		data.put(14,"Frasergunje");
		data.put(15,"FrezerganjFH");
		data.put(16,"Lothian Island");
		data.put(17,"Bakkhali");
		landingcenters.add(10,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Landfall");
		data.put(2,"Narcondam");
		data.put(3,"Diglipur");
		data.put(4,"Laxmipur,Diglipur");
		data.put(5,"ArealBay,Diglipur");
		data.put(6,"Durgapur");
		data.put(7,"Kalipur,Diglipur");
		data.put(8,"Kalighat,Diglipur");
		data.put(9,"Pokadera");
		data.put(10,"Mayabunderproper");
		data.put(11,"Webi,Mayabunder");
		data.put(12,"Tugapur,Mayabunder");
		data.put(13,"Betapur(RRO)");
		data.put(14,"Rangat Bay");
		data.put(15,"KaushalyaNagar");
		data.put(16,"Dashratpur");
		data.put(17,"Yerrata");
		data.put(18,"Long Island");
		data.put(19,"Elphinstone Hr");
		data.put(20,"Uttara");
		data.put(21,"OralKatcha");
		data.put(22,"Barren");
		data.put(23,"Havelock");
		data.put(24,"Middle Strait");
		data.put(25,"ShoalBay");
		data.put(26,"Wrightmyo");
		data.put(27,"Neil Island");
		data.put(28,"Port Blair");
		data.put(29,"Bambooflat");
		data.put(30,"Haddo");
		data.put(31,"Hope Town");
		data.put(32,"Dunduspoint");
		data.put(33,"Phoenix Bay");
		data.put(34,"Junglighat");
		data.put(35,"Dignabad");
		data.put(36,"Mt Haughton");
		data.put(37,"Lohabarrack");
		data.put(38,"Chouldari");
		data.put(39,"Wandoor");
		data.put(40,"Chidiyatapu");
		data.put(41,"Rutland");
		data.put(42,"Cinque Island");
		data.put(43,"Tambe-e-bul");
		data.put(44,"Vivekanandpur,LittleAndaman");
		data.put(45,"RamaKrishnaPur,");
		data.put(46,"Kwate-tu-Kwage");
		data.put(47,"Harminder Bay");
		data.put(48,"Machidera(Hutbay),");
		data.put(49,"Benyaboi");
		data.put(50,"Tula");
		data.put(51,"Tochangeou");
		data.put(52,"Ten Degree Channel");
		data.put(53,"Coco Channel");
		landingcenters.add(11,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Keating Pt (Car Nicobar)");
		data.put(2,"Mus,CarNicobar");
		data.put(3,"Sawai (Car Nicobar)");
		data.put(4,"Teetop,CarNicobar");
		data.put(5,"Passa, Car Nicobar");
		data.put(6,"Arrong (Car Nicobar)");
		data.put(7,"Malacca,CarNicobar");
		data.put(8,"Batti Malv");
		data.put(9,"Chowra");
		data.put(10,"Aoang");
		data.put(11,"Laksi");
		data.put(12,"Bampoka");
		data.put(13,"Kai-Hoa");
		data.put(14,"Takaroach");
		data.put(15,"Trinket,Nancowry");
		data.put(16,"Kamorta,Nancowry");
		data.put(17,"Hitui,Nancowry");
		data.put(18,"Champion,Nancowry");
		data.put(19,"Balubasti, Nancowry Island");
		data.put(20,"Attabiak, Nancowry Island");
		data.put(21,"Tapong, Nancowry Island");
		data.put(22,"Cape Connaught");
		data.put(23,"Kapanga, Katchall");
		data.put(24,"Katchal East Bay");
		data.put(25,"Jansin");
		data.put(26,"Katchal West Bay");
		data.put(27,"Sombrero Pt");
		data.put(28,"Pulo Patia");
		data.put(29,"Kabra Pt");
		data.put(30,"Tenlaa");
		data.put(31,"Rosen Pt");
		data.put(32,"CampbellBay");
		data.put(33,"Vijoy Nagar");
		data.put(34,"Indira Pt");
		data.put(35,"Kokeon");
		data.put(36,"Pulo Kunji");
		data.put(37,"Ten Degree Channel");
		data.put(38,"Great Channel");
		landingcenters.add(12,data);
		alllandingcenters.addAll(data.values());
		data = new LinkedHashMap<Integer, String>();
		data.put(1,"Valiyapani reef");
		data.put(2,"Byramgore");
		data.put(3,"Cheriyapani reef");
		data.put(4,"Chetlat I");
		data.put(5,"Bitra I");
		data.put(6,"Kiltani");
		data.put(7,"Perumalpar reef");
		data.put(8,"Kadmath I");
		data.put(9,"Amini I");
		data.put(10,"Tinnakara");
		data.put(11,"Bangaram I");
		data.put(12,"Agatti I");
		data.put(13,"Androth I");
		data.put(14,"Kavaratti I");
		data.put(15,"Valiykara");
		data.put(16,"Suheli");
		data.put(17,"Cheriyakara");
		data.put(18,"Kalpeni I");
		data.put(19,"Minicoy");
		landingcenters.add(13,data);
		alllandingcenters.addAll(data.values());
	}

}
